### ISSUE TITLE
Safetensors metadata remote reader

### ISSUE THREAD

**Issue by LysandreJik** [huggingface/huggingface_hub#1832] opened 2023-11-16 15:28 UTC
`safetensors` is the chosen de/serialization method for the Hugging Face Hub. Moving forward, to guarantee the Hub remains a safe place for users, we'll encourage repositories to use this file type.

Safetensors files are designed to support several frameworks for their serialization: PyTorch, Flax, TensorFlow, NumPy, for now.

Knowing ahead of time what framework was used at serialization can be very useful for end-users and frameworks so as to know if the checkpoint will be usable without downloading the entire checkpoint.

It can be done by checking the first 8 bytes of the checkpoint which indicates the length of the metadata, and to load that metadata afterwards. It is implemented in huggingface.js here: https://huggingface.co/docs/safetensors/metadata_parsing

Would be awesome to have it in `huggingface_hub` as well.

cc @Wauplin @Narsil

**Comment by julien-c** [comment] 2023-11-17 09:13
JS implem is there: https://github.com/huggingface/huggingface.js/blob/main/packages/hub/src/lib/parse-safetensors-metadata.ts

**Comment by Wauplin** [comment] 2023-11-17 11:20
Thanks for the link @julien-c. I've looked into it and I'm not sure it's necessary for the use case @LysandreJik described. As far as I understand JS implementation takes a model id and:
-  parses the `"model.safetensors.index.json"` file (if any), read all safetensors metadata and group them together
- or parses a single `"model.safetensors"`

Which is quite opinionated on the repo format (it has to have a single safetensor file or a single index). It's understandable since it was designed for the Hub UI first (afaik).

In the case of a Python parser I would prefer to have a simple parser that takes repo_id+filename and returns the metadata without assuming any repo format. If we have the need for a JS-like method in the future we can always build on top of it.

Something like that (more or less)

```py
def get_safetensors_metadata(repo_id: str, filename: str, *, repo_type: Optional[str] = None, revision: Optional[str] = None) -> dict:
    url = hf_hub_url(repo_id=repo_id, filename=filename, repo_type=repo_type, revision=revision)

    # Fetch metadata size
    response= get_session().get(url, headers={"range": "bytes=0-7"})
    hf_raise_for_status(response)
    metadata_size = int.from_bytes(response.content, "little")

    # Fetch metadata
    response= get_session().get(url, headers={"range": f"bytes=8-{metadata_size+7}"})
    hf_raise_for_status(response)
    return response.json()
```

**Comment by julien-c** [comment] 2023-11-17 11:43
sure, it's a strict subset of the JS implementation then

> Which is quite opinionated on the repo format

i do think this is generally good as it forces the sane convention of everyone using mostly the same filenames which has proven useful in the past.

As an example, on the Hub we only detect as safetensors the repos containing `safetensors = "model.safetensors*",` filenames.

I have a philosophical intuition that having strong conventions on filenames makes models less fragmented (for instance, it's more natural to have one repo per model than if you have arbitrary files)

**Comment by Wauplin** [comment] 2023-12-15 17:51
Closed by https://github.com/huggingface/huggingface_hub/pull/1855.

**Closed by Wauplin** 2023-12-15 17:51 UTC
