### ISSUE TITLE
No module found huggingface_hub.snapshot_download in 0.11.0

### ISSUE THREAD

**Issue by josephsachdeva** [huggingface/huggingface_hub#1199] opened 2022-11-18 10:44 UTC
### Describe the bug

We have the sentence_transformer version: 2.22.0 and it is by default downloading the huggingface_hub version 0.11.0
But it is giving error.

We tried using huggingface_hub==0.10.0 and it is working fine.

### Reproduction

install sentence-transformers==2.22.0

### Logs

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/datasets/__init__.py", line 3, in <module>
    from .ParallelSentencesDataset import ParallelSentencesDataset
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/datasets/ParallelSentencesDataset.py", line 4, in <module>
    from .. import SentenceTransformer
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/SentenceTransformer.py", line 25, in <module>
    from .evaluation import SentenceEvaluator
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/evaluation/__init__.py", line 5, in <module>
    from .InformationRetrievalEvaluator import InformationRetrievalEvaluator
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/evaluation/InformationRetrievalEvaluator.py", line 6, in <module>
    from ..util import cos_sim, dot_score
  File "/usr/local/lib/python3.8/site-packages/sentence_transformers/util.py", line 407, in <module>
    from huggingface_hub.snapshot_download import REPO_ID_SEPARATOR
ModuleNotFoundError: No module named 'huggingface_hub.snapshot_download'
```

### System info

```shell
huggingface_hub version: 0.11.0
sentence_transformers version: 2.22.0
```

**Comment by Wauplin** [comment] 2022-11-18 11:17
Hi @josephsachdeva, sorry for the inconvenience. `snapshot_download` module has been removed from `huggingface_hub` in favor of a private `_snapshot_download` module. A deprecation warning should have been triggered since a few versions now to warn about this.

The workaround here is to import `REPO_ID_SEPARATOR` from the `constants` module:
```py
from huggingface_hub.constants import REPO_ID_SEPARATOR
```

Otherwise, you can temporarily pin `huggingface_hub` version to `==0.10` in a hot-fix, while you update the code in parallel. For the record, `huggingface_hub==0.11.0` has been released on Wednesday (16/11/2022).

**Comment by josephsachdeva** [comment] 2022-11-22 07:28
Hi @Wauplin thanks for replying!
Actually we are not using huggingface_hub directly, it is being used in sentence_transformers. And i think the workaround you suggested will be done by sentence_transformers devs.

But yes, we have downgraded huggingface_hub to 0.10.0 and it is working fine for us.

Thanks.

**Comment by Wauplin** [comment] 2022-11-22 12:24
@josephsachdeva actually the problem is already fixed in `sentence_transformers`. If possible for you, I'd advice to update to latest version. See related issue https://github.com/UKPLab/sentence-transformers/issues/1599#issuecomment-1164371279.

**Closed** 2022-11-22 12:24 UTC
Labels: bug
