### ISSUE TITLE
Adding/approving model repo access via API

### ISSUE THREAD

**Issue by RonanKMcGovern** [huggingface/huggingface_hub#1749] opened 2023-10-16 11:03 UTC
### System Info

latest

### Who can help?

@stevhliu and @MKhalusova

### Information

- [ ] The official example scripts
- [ ] My own modified scripts

### Tasks

- [ ] An officially supported task in the `examples` folder (such as GLUE/SQuAD, ...)
- [ ] My own task or dataset (give details below)

### Reproduction

For a gated repo, is it possible to add users via api?

I'm searching through the [docs](https://huggingface.co/docs/huggingface_hub/main/en/package_reference/hf_api) and not seeing anything.

Thanks.

### Expected behavior

Option to add users to a gate repo via api.

**Comment by Wauplin** [comment] 2023-10-16 14:33
@RonanKMcGovern would the solution described in https://github.com/huggingface/huggingface_hub/issues/1535#issuecomment-1614693412 works for you? It is not implemented for now as we got very few requests (and is quite niche atm). If you are talking about something else, please let me know.

**Comment by Wauplin** [comment] 2023-10-16 17:59
You can run it as it is! It will not be implemented/merged in the coming weeks I think as we prefer not to push it officially (low usage and that would constrain us if we want to change the API in the future).

I'll close this issue as duplicate of https://github.com/huggingface/huggingface_hub/issues/1535. Please let me know if you need to reopen.

**Closed by Wauplin** 2023-10-16 17:59 UTC
