### ISSUE TITLE
Downloaded File Contents from Repository Do Not Match SHA-256 and File Size

### ISSUE THREAD

**Issue by donald-pinckney** [huggingface/huggingface_hub#1445] opened 2023-04-22 16:08 UTC
### Describe the bug

I'm not sure if this is a bug in the `huggingface_hub` library necessarily, but in the underlying Git LFS file storage. For a handful of files that I uploaded using `HfApi.create_commit`, the file metadata (file size and SHA-256) listed in the HF repo  **does not match** that metadata after downloading the file. 

In essence, it appears that HF returns a file size and SHA-256 of the data I had uploaded, but when downloading the data serves a corrupted file.

### Reproduction

1. Open this link: [https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-986](https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-986)

2. By looking at the "Raw pointer file", you can see that HF reports a size of 48,000,000,000 bytes and a SHA-256 of `6d1265ec043b854a454f6c3b14eeee0de11ef180b6bc1b3e6d718c7e20579fc8`. Alternatively, you can check this via: 
```
huggingface_hub.get_hf_file_metadata("https://huggingface.co/datasets/nuprl/npm-follower-data/resolve/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-986")
```

3. Download the actual file.

4. Check the file size of the downloaded file, and notice that the size is only 47,971,606,528 bytes instead of 48,000,000,000:
```
$ ls -l 29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-986
-rw-r--r--@ 1 donaldpinckney  staff  47971606528 Apr 22 11:55 29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-986
```

5. Compute the SHA-256 of the downloaded file and note that the compute SHA does not match:
```
$ shasum -a 256 29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-986
83e6008c84c1ccb5fd40c8412d8a6550931290306d47e7be21966b6a767d5604  29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-986
```

To be clear, the data that I had *actually uploaded* was 48,000,000,000 bytes, so it appears that somewhere along the way HF stored an incorrect / corrupted file, but kept the original metadata.

### System info

```shell
The upload was performed in the following environment. But the corrupted metadata & download persists regardless of how you download the data file.

- huggingface_hub version: 0.13.4
- Platform: Linux-3.10.0-1160.25.1.el7.x86_64-x86_64-with-glibc2.2.5
- Python version: 3.8.1
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/pinckney.d/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: donald-pinckney
- Configured git credential helpers:
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: N/A
- Graphviz: N/A
- Pydot: N/A
- Pillow: N/A
- hf_transfer: N/A
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/pinckney.d/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/pinckney.d/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/pinckney.d/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by donald-pinckney** [comment] 2023-04-22 16:17
Also, I should note that this wasn't an isolated incident. It occurred with 11 files in that repository:

```
https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-289
metadata bytes = 39321304576, downloaded bytes = 39291600384

https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-294
metadata bytes = 29668224344, downloaded bytes = 29655510360

https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-7
metadata bytes = 22971348330, downloaded bytes = 22958921066

https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-759
metadata bytes = 32277620965, downloaded bytes = 32276654309

https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-772
metadata bytes = 21250826144, downloaded bytes = 21241667488

https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-774
metadata bytes = 21060650111, downloaded bytes = 21041112191

https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-836
metadata bytes = 32648040686, downloaded bytes = 32634949870

https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-851
metadata bytes = 23691714171, downloaded bytes = 23681465979

https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-853
metadata bytes = 20350548770, downloaded bytes = 20340874018

https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-981
metadata bytes = 38580570310, downloaded bytes = 38570961094

https://huggingface.co/datasets/nuprl/npm-follower-data/blob/v1.0.0-apr-17-2023/.avc/blobs/29/29a4d0a631669c4dfbf22b009995658ebe45f7a2a5caf23aebdd38283d687960-blob-986
metadata bytes = 48000000000, downloaded bytes = 47971606528
```

**Comment by donald-pinckney** [comment] 2023-04-22 17:08
To make matters worse, this also prevents me from re-uploading the corrupted files. `HfApi.create_commit` checks the SHAs, and since the locally computed SHA matches the cached HF SHA, it skips the upload.

**Comment by Wauplin** [comment] 2023-04-26 07:44
Hi @donald-pinckney , thanks for reporting this issue and sorry for the delay to answer. The problem seems to be come from the fact that "something" happened during the upload resulting in some bytes not being saved on S3 but without raising an exception (neither in `huggingface_hub` or from the Hub directly).

I have been able to reproduce this issue on a much smaller file for easier debugging. Uploaded file has size 16M while the Hub expects 70M: https://huggingface.co/Wauplin/test-corrupted-lfs-file/blob/main/file.bin. File sha256 is of course corrupted in this case. Let me check with the server team to find a solution for this.

> To make matters worse, this also prevents me from re-uploading the corrupted files. HfApi.create_commit checks the SHAs, and since the locally computed SHA matches the cached HF SHA, it skips the upload.

Yes indeed, I see the problem here. LFS files are kept on S3 as long as the repo exists. So if you want to re-upload them, you'll need to either delete and recreate the repo or do another split of the files (and re-upload). In general, it's a better practice to split your big files in chunks of ~10GB for better caching. I understand that both solutions are not very appealing at the moment but that's all I have for now :confused:

**Comment by Wauplin** [comment] 2023-04-27 07:58
That's indeed a nice way of reproducing the bug, thanks for sharing the code snippet.

I reported the bug internally (https://github.com/huggingface/moon-landing/issues/5885) but I can't promise on when it will be fixed. We have to have a way server-side to block files if the size/sha256 of the uploaded content is not the one expected but the logic to do that have to be discussed.

cc @Pierrci @coyotte508 for visibility

**Comment by julien-c** [comment] 2023-04-27 14:06
yep it's on our radar, thanks for reporting @donald-pinckney

**Comment by Wauplin** [comment] 2023-06-30 14:36
@donald-pinckney We've now added a check server-side to address this issue [in this PR](https://github.com/huggingface/moon-landing/pull/6813) (internal link). The server now rejects the commit entirely if one of the LFS files has not been correctly uploaded. A HTTP 400 BadRequest is returned:

```
huggingface_hub.utils._errors.BadRequestError:  (Request ID: 1251b384-ded1-49e4-b05c-6dbfec8cc308)

Bad request for commit endpoint:
Your push was rejected because an LFS pointer pointed to a file that does not exist. For instance, this can happen if you used git push --no-verify to push your changes. Offending file: - file_50MB.bin
```

If the user tries to make the same commit again, the LFS files are re-uploaded.

**Closed by Wauplin** 2023-06-30 14:36 UTC
Labels: bug
