### ISSUE TITLE
Unable to acquire file lock in some situations

### ISSUE THREAD

**Issue by Sogomn** [huggingface/huggingface_hub#1423] opened 2023-04-05 16:34 UTC
### Describe the bug

[This](https://github.com/huggingface/huggingface_hub/blob/7a3e1e8580b86a61c4dc5f3c5e24ae6c0c0028fa/src/huggingface_hub/file_download.py#L1304) can cause hangs if Windows doesn't like the `lock_path` (see #35).

If the `etag` received contains certain characters (`"`, `/`), the `blob_path` (and in turn the `lock_path`) will contain those which causes the file lock to hang.
The problem I encountered with this was solved by sanitizing the `etag` passed to the `blob_path` [here](https://github.com/huggingface/huggingface_hub/blob/7a3e1e8580b86a61c4dc5f3c5e24ae6c0c0028fa/src/huggingface_hub/file_download.py#L1270) so that it doesn't contain any characters that aren't allowed in file names.

### Reproduction

No clue, seems to be a very special case.

### System info

```shell
- Windows 11
- Python 3.10.11
- main
```

**Comment by Wauplin** [comment] 2023-04-05 16:55
Hi @Sogomn, thanks for reporting the issue. Could you tell me when this arrived to you? (which repo? which file?). Reproducing it shouldn't be too difficult if we have an example of problematic etag.

> this was solved by sanitizing the etag passed to the blob_path [here](https://github.com/huggingface/huggingface_hub/blob/7a3e1e8580b86a61c4dc5f3c5e24ae6c0c0028fa/src/huggingface_hub/file_download.py#L1270)

Interested in opening a PR to fix it and add a test? We'll need a breaking example first. I can help if needed :)

**Comment by ahjulstad** [comment] 2023-04-05 17:52
I encounter the same issue when trying LORA training in kohya_ss with a SD2.1 model, specifically, it tries to acquire lock:

```
C:\Users\asmun/.cache\huggingface\hub\models--stabilityai--stable-diffusion-2\blobs\W/"469be27c5c010538f845f518c4f5e8574c78f7c8.lock
```

If I try a workaround to rename the lock file it is unable to download:
```
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\asmun\\.cache\\huggingface\\hub\\tmp2a9dqnzs' -> 'C:\\Users\\asmun/.cache\\huggingface\\hub\\models--stabilityai--stable-diffusion-2\\blobs\\W/"469be27c5c010538f845f518c4f5e8574c78f7c8'
```

**Comment by ahjulstad** [comment] 2023-04-05 18:27
A very ugly fix  [here](https://github.com/ahjulstad/huggingface_hub/tree/rename-etag)

**Comment by Sh4rK** [comment] 2023-04-05 21:06
Hi, I spent several hours trying to install InvokeAI and AUTOMATIC1111 WebUI and always got to a point where they just hang forever, and this turned out to be the cause, verified by the fix above. The problem is that no error was printed anywhere, I could only look at the stacktrace after killing the process.

Just adding it for visibility that this affects more than 1 person :)

**Comment by Sh4rK** [comment] 2023-04-05 21:19
Looks like https://pathvalidate.readthedocs.io could be used here to non-hackily sanitize the file name, is it okay to add this as a dependency? If yes, I can throw together a PR sometime.

**Comment by dwforbes** [comment] 2023-04-06 03:31
The function _normalize_etag in file_download.py includes the following text describing an assumption-

>    The HTTP spec allows two forms of ETag:
      ETag: W/"<etag_value>"
      ETag: "<etag_value>"

>    The hf.co hub guarantees to only send the second form.

This is not currently true. The server is currently returning Etags in forms such as W/"1f1d9aaca301414e7f6c9396df506798ff4eb9a6".

Because of the unexpected leading W/ the etag.strip('"') is failing to strip the first quotation mark, yielding paths that are invalid on Windows.

Given the variants the ideal fix would be to strip possibly leading W/ before doing the quotation strip.

**Comment by toncho11** [comment] 2023-04-06 07:09
I have the same problem on Windows.
The metadata.etag is: W/"2ea941cc79a6f3d7985ca6991ef4f67dad62af04

So it can not create the lock:  \\.cache\\huggingface\\hub\\models--distilbert-base-cased-distilled-squad\\blobs\\W/"2ea941cc79a6f3d7985ca6991ef4f67dad62af04.lock

And the worst is that it keeps trying forever evey 50ms without any error message on the screen.

**Comment by toncho11** [comment] 2023-04-06 08:04
I tried pull request #1428 and it fixed my problem:

`pip install git+https://github.com/huggingface/huggingface_hub.git@refs/pull/1428/head`

A quick look shows that both #1427 and #1428 do the same thing.

**Comment by Wauplin** [comment] 2023-04-06 08:12
Thanks a lot everyone here for reporting the issue, finding some alternatives, making a PR and testing it :heart: 

Sorry for the inconvenience on this. The problem most probably comes from some configuration changed server-side. Since this is affecting all previous versions of `huggingface_hub`, it would be best to fix it on our side rather than publishing a hot-fix for each version of hfh. In any case, I'll keep you updated about the progress.

In the meantime, a good workaround is to install huggingface_hub from source from https://github.com/huggingface/huggingface_hub/pull/1428:
```
pip install git+https://github.com/dwforbes/huggingface_hub@main
```

**Comment by Wauplin** [comment] 2023-04-06 08:40
**Update**: issue has been fixed server-side. Thanks for reporting it :)

PR https://github.com/huggingface/huggingface_hub/pull/1428 will still be merged to handle this case in the future. 
I'm now closing this issue but feel free to re-open if you still have issues on this matter.

**Closed by Wauplin** 2023-04-06 08:40 UTC
Labels: bug

**Comment by henk717** [comment] 2023-06-21 19:10
This bug has resurfaced, updating to the latest huggingface_hub solves it but we have some repo's still depending on older versions until we are ready for the update.

**Comment by Strahammer** [comment] 2023-06-21 19:26
> This bug has resurfaced, updating to the latest huggingface_hub solves it but we have some repo's still depending on older versions until we are ready for the update.

I thought I was going crazy for the past several hours.

**Comment by besrabird** [comment] 2023-06-21 23:29
Confirm that the issue has resurfaced. @Wauplin Did something change again server-side?

**Comment by BramVanroy** [comment] 2023-06-23 13:34
I can also confirm. I tried with the most recent version down to 0.12.1.

**Comment by Wauplin** [comment] 2023-06-26 08:53
Thanks @henk717 @Strahammer @besrabird @BramVanroy for the ping and letting us know. Some models/files were indeed affected since Friday. It has now been fixed server-side so this bug on Windows shouldn't happen again. As @BramVanroy said, the best way to ensure a future-proof compatibility is to update the client library to `huggingface_hub>=0.15` version which includes a client-side fix. Sorry again for the inconvenience and hope it doesn't resurface anymore :)
