### ISSUE TITLE
huggingface-cli login，ConnectionResetError: [WinError 10054] 

### ISSUE THREAD

**Issue by huyunan496** [huggingface/huggingface_hub#1517] opened 2023-06-19 10:13 UTC
### Describe the bug

 D:\stable-dreamfusion-main> huggingface-cli login --token xxxxx
Token will not been saved to git credential helper. Pass `add_to_git_credential=True` if you want to set the git credential as well.
Traceback (most recent call last):
  File "D:\Python310\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Python310\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "D:\Python310\lib\site-packages\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "D:\Python310\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "D:\Python310\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\Python310\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Python310\lib\ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Python310\lib\ssl.py", line 1071, in _create
    self.do_handshake()
  File "D:\Python310\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

### System info

```shell
- huggingface_hub version: 0.15.1
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.10.11
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: C:\Users\zhoukang\.cache\huggingface\token
- Has saved token ?: False
- Configured git credential helpers: manager-core
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.0+cu118
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.5.0
- hf_transfer: N/A
- gradio: N/A
- numpy: 1.24.3
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: C:\Users\zhoukang\.cache\huggingface\hub
- HUGGINGFACE_ASSETS_CACHE: C:\Users\zhoukang\.cache\huggingface\assets
- HF_TOKEN_PATH: C:\Users\zhoukang\.cache\huggingface\token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment] 2023-06-26 10:54
Hi @huyunan496, sorry that your experiencing this issue. Usually this can be due to either by your local setup (are you behind a proxy for example?) or a short outage on our server. Would you be able to retry and tell us if it happens again with the exact same error?

**Comment by Wauplin** [comment] 2023-07-11 09:39
Closing as no more information since 3 weeks. I hope the problem is now solved on your side. Feel free to re-open if needed :)

**Closed by Wauplin** 2023-07-11 09:39 UTC
Labels: bug

**Comment by WDJY-Autumn** [comment] 2025-01-09 09:40
The token has not been saved to the git credential helper. Pass 'add_to_git_credential=true' in this function directly or '--add-to-git-credential' if using via 'huggingface-cli' if you want to set the git credential as well
