### ISSUE TITLE
"import transformers"出现问题

### ISSUE THREAD

**Issue by chenkang404** [huggingface/huggingface_hub#1434] opened 2023-04-12 08:19 UTC
ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant'

**Comment by Wauplin** [comment] 2023-04-12 09:11
Hi @chenkang404, could you provide more information please?

In particular, which version of `huggingface_hub` are you using? The best would be to run `huggingface-cli env` and copy-paste the output here.

Also, could you provide a snippet of code that reproduces the error? And the full stacktrace instead of just the error message? 

In the current state, it's hard to provide any help :confused:

**Comment by chenkang404** [comment] 2023-04-12 09:22
try "pip install chardet", the issue is clear
&nbsp;yet:
"from transformers import LlamaForCausalLM,LlamaTokenizer" 
ImportError: cannot import name 'LlamaForCausalLM' from 'transformers'&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huggingface/huggingface_hub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月12日(星期三) 下午5:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huggingface/huggingface_hub] "import transformers"出现问题 (Issue #1434)





 
Actually the issue is much likely to be the same as the one reported in huggingface/transformers#21858.
 
Could you try pip install chardet as mentioned in huggingface/transformers#21858 (comment) ?

**Comment by Wauplin** [comment] 2023-04-12 09:28
> ImportError: cannot import name 'LlamaForCausalLM' from 'transformers'&nbsp;

This is a different issue. I don't think you have the latest versions installed. Try running

```
pip install --upgrade huggingface_hub
pip install --upgrade transformers
``` 

> the issue is clear

No it's not so clear to me to be honest

**Comment by chenkang404** [comment] 2023-04-12 09:31
"pip install git+https://github.com/huggingface/transformers.git"

my install transformers running


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huggingface/huggingface_hub"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月12日(星期三) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huggingface/huggingface_hub] "import transformers"出现问题 (Issue #1434)





  
ImportError: cannot import name 'LlamaForCausalLM' from 'transformers'&nbsp;
  
This is a different issue. I don't think you have the latest versions installed. Try running
 pip install --upgrade huggingface_hub pip install --upgrade transformers   
the issue is clear
  
No it's not so clear to be honest

**Comment by Wauplin** [comment] 2023-04-12 09:53
I'm sorry but I don't what your problem is.
If you want some help, please send a complete explanation of your setup and your problem.

**Comment by Wauplin** [comment] 2023-04-17 07:41
I'm closing this issue because of lack of information
@chenkang404 you can re-open it if you want. If you do so, please provide better context about the issue:
- a snippet of code to reproduce the issue
- the full stacktrace of the error
- a list of your dependencies (ie. copy-paste the output of `pip freeze`)
- the output of `huggingface-cli env` 
- the output of `transformers-cli env`

**Closed by Wauplin** 2023-04-17 07:41 UTC
