### ISSUE TITLE
push_to_hub_keras error 

### ISSUE THREAD

**Issue by lmxhappy** [huggingface/huggingface_hub#1239] opened 2022-12-02 03:19 UTC
### Describe the bug

I made a keras model and call push_to_hub_keras to upload, a error happens like this:
`OSError: Unable to create file (unable to open file: name = 'my_tmp2', errno = 21, error message = 'Is a directory', flags = 13, o_flags = 602)`

### Logs

```shell
` File "/Users/conan/Desktop/codes/topic_relationship/classify/training/my_test_model.py", line 108, in <module>
    main()
  File "/Users/conan/Desktop/codes/topic_relationship/classify/training/my_test_model.py", line 103, in main
    push_to_hub_keras(model, "my_tmp2", "lmxhappy/my_tmp2")
  File "/Users/conan/opt/anaconda3/envs/py36-tf1.13/lib/python3.6/site-packages/huggingface_hub/keras_mixin.py", line 153, in push_to_hub_keras
    save_pretrained_keras(model, repo_path_or_name, config=config)
  File "/Users/conan/opt/anaconda3/envs/py36-tf1.13/lib/python3.6/site-packages/huggingface_hub/keras_mixin.py", line 53, in save_pretrained_keras
    tf.keras.models.save_model(model, save_directory)
  File "/Users/conan/opt/anaconda3/envs/py36-tf1.13/lib/python3.6/site-packages/tensorflow/python/keras/engine/saving.py", line 93, in save_model
    f = h5py.File(filepath, mode='w')
  File "/Users/conan/opt/anaconda3/envs/py36-tf1.13/lib/python3.6/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/Users/conan/opt/anaconda3/envs/py36-tf1.13/lib/python3.6/site-packages/h5py/_hl/files.py", line 179, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 108, in h5py.h5f.create
OSError: Unable to create file (unable to open file: name = 'my_tmp2', errno = 21, error message = 'Is a directory', flags = 13, o_flags = 602)

`
```

### System info

```shell
huggingface-cli: error: invalid choice: 'env' (choose from 'login', 'whoami', 'logout', 'repo', 'lfs-enable-largefiles', 'lfs-multipart-upload')
```

**Comment by Wauplin** [comment] 2022-12-02 09:19
Hi @lmxhappy , thanks for reporting.

It seems that you are running on an outdated version of `huggingface_hub`. Would you be able to upgrade it to latest version (`0.11.1`) ? You should be able to run `huggingface-cli env` which would help debug your case. Also I expect the stacktrace to slighly change so could you rerun and set an updated version of it ? Thanks in advance ! :pray:

**Comment by merveenoyan** [comment] 2022-12-02 11:34
@lmxhappy can you post your code as well so I can reproduce? (as @Wauplin said) seems like there might be a problem with args.

**Comment by Wauplin** [comment] 2023-01-19 10:13
I'm closing this issue for lack of information. Reported bug is most probably due to usage of an older version of `hfh`. Feel free to re-open it if the bug persists.

**Closed as completed by Wauplin** 2023-01-19 10:13 UTC
Labels: bug
