### ISSUE TITLE
Inconsistency error occurred when downloading the model from the Hugging Face space

### ISSUE THREAD

**Issue by narugo1992** [huggingface/huggingface_hub#1521] opened 2023-06-21 04:41 UTC
### Describe the bug

When I tried to download the model from [my Hugging Face space](https://huggingface.co/spaces/deepghs/anime_image_classification), I encountered the following error (see Logs part). It seems to be caused by incomplete model download, and even after multiple restarts of the Hugging Face space, the issue persists

### Reproduction

Enter [my Hugging Face space](https://huggingface.co/spaces/deepghs/anime_image_classification), switch to "Character Horns" tab, use model `caformer_s36_v0`, put an image inside the "Original Image" block, click "submit", error will occurred.

The model being used is https://huggingface.co/deepghs/anime_ch_horn/blob/main/caformer_s36_v0/model.onnx

This error can be reproduced with the following code (`huggingface_hub`'s version should be `0.15.1` or `0.14.1`).
```python
from huggingface_hub import hf_hub_download

if __name__ == '__main__':
    file = hf_hub_download(
        'deepghs/anime_ch_horn',
        'caformer_s36_v0/model.onnx'
    )

    print(file)
```

Additionally:
* no other models, except for this one, encountered a similar error on Hugging Face space.
* when I downgrade the `huggingface_hub`'s version to `0.13.2`, it's okay
* it can be also reproduced in [jupyterlab deployed on huggingface space](https://huggingface.co/spaces/narugo/jupyterlab) (password is `password`)

### Logs

```shell
Downloading (…)6a1e6c7eb34b3424d7d1:   0%|          | 0.00/142M [00:00<?, ?B/s]
Downloading (…)6a1e6c7eb34b3424d7d1:  15%|█▍        | 21.0M/142M [00:00<00:00, 135MB/s]
Downloading (…)6a1e6c7eb34b3424d7d1:  29%|██▉       | 41.9M/142M [00:00<00:01, 75.7MB/s]
Downloading (…)6a1e6c7eb34b3424d7d1:  37%|███▋      | 52.4M/142M [00:00<00:01, 68.7MB/s]
Downloading (…)6a1e6c7eb34b3424d7d1:  44%|████▍     | 62.9M/142M [00:00<00:01, 65.5MB/s]
Downloading (…)6a1e6c7eb34b3424d7d1:  59%|█████▉    | 83.9M/142M [00:01<00:00, 69.1MB/s]
Downloading (…)6a1e6c7eb34b3424d7d1:  66%|██████▋   | 94.4M/142M [00:01<00:00, 57.3MB/s]
Downloading (…)6a1e6c7eb34b3424d7d1:  74%|███████▎  | 105M/142M [00:01<00:00, 58.2MB/s] 
Downloading (…)6a1e6c7eb34b3424d7d1:  88%|████████▊ | 126M/142M [00:01<00:00, 59.1MB/s]
Downloading (…)6a1e6c7eb34b3424d7d1:  96%|█████████▌| 136M/142M [00:02<00:00, 59.1MB/s]Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/gradio/routes.py", line 374, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 1017, in process_api
    result = await self.call_function(
  File "/home/user/.local/lib/python3.8/site-packages/gradio/blocks.py", line 835, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/user/app/base.py", line 43, in _gr_classification
    model, labels = self._open_onnx_model(model_name)
  File "/home/user/app/base.py", line 38, in _open_onnx_model
    return open_model_from_repo(self.repository, model)
  File "/home/user/app/base.py", line 19, in open_model_from_repo
    runtime = _open_onnx_model(hf_hub_download(repository, f'{model}/model.onnx'))
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1364, in hf_hub_download
    http_get(
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 547, in http_get
    raise EnvironmentError(
OSError: Consistency check failed: file should be of size 149615684 but has size 142259268 ((…)6a1e6c7eb34b3424d7d1).
We are sorry for the inconvenience. Please retry download and pass `force_download=True, resume_download=False` as argument.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub.
```

### System info

This is my local environment:

- huggingface_hub version: 0.14.1
- Platform: Linux-5.15.0-75-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.7.6
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/narugo/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: 1.13.1
- Jinja2: 3.0.3
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.5.0
- hf_transfer: N/A
- gradio: N/A
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/narugo/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/narugo/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/narugo/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False

This is the environment in [jupyterlab deployed on huggingface space](https://huggingface.co/spaces/narugo/jupyterlab)

- huggingface_hub version: 0.14.1
- Platform: Linux-5.10.167-147.601.amzn2.x86_64-x86_64-with-glibc2.2.5
- Python version: 3.8.1
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/user/.cache/huggingface/token
- Has saved token ?: False
- Configured git credential helpers: 
- FastAI: N/A
- Tensorflow: N/A
- Torch: N/A
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.5.0
- hf_transfer: N/A
- gradio: N/A
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/user/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/user/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/user/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False

**Comment by Wauplin** [comment] 2023-06-21 07:21
Hi @narugo1992 , it seems that for some reason the uploaded file is not correct. When uploading it, a file of 142M was expected (from lfs pointer info) but only 136M have been uploaded to S3. For some reason, your upload script did not complain.

At some point in https://github.com/huggingface/huggingface_hub/issues/1445, we discussed the idea of checking the S3 file consistency (size + sha256) on the server before creating the commit (cc @julien-c @Pierrci).

```py
>>> import requests
>>> from huggingface_hub import get_hf_file_metadata, hf_hub_url

# Information stored in HF pointer file
>>> url = hf_hub_url(repo_id="deepghs/anime_ch_horn", filename="caformer_s36_v0/model.onnx")
>>> metadata = get_hf_file_metadata(url)
>>> metadata.size
149615684

# Information from the S3 file
>>> response = requests.head(metadata.location)
>>> response.headers["Content-Length"]
142259268
```

---

When you say that downgrading to `huggingface_hub==0.13` fixes your issue, it is because in earlier versions we were not checking consistency of the file size when downloading it. Maybe we should remove this check in `huggingface_hub` but I'd still be interested in knowing why this issue happens in the first place. When you downgrade to `0.13`, is your Space working correctly? If the file is truncated, it shouldn't be able to load the model, right?
Also out of curiosity, how did you upload the weights file? (script or browser?)

**Comment by Wauplin** [comment] 2023-06-21 07:25
About a quick fix for your issue, I would try to re-upload the corrupted file. If you try to re-upload exactly the same one it will not work because the Hub already think it has the same file on S3 (since we check based on file size/sha256 stored in git repo, not from S3). What you can do is to upload a slightly different file with the same name (for example, update just a metadata value inside it?)

**Comment by narugo1992** [comment] 2023-06-21 10:47
> Also out of curiosity, how did you upload the weights file? (script or browser?)

I uploaded the model file using huggingface_hub, and the code can be found here: https://github.com/deepghs/classification/blob/main/classification/publish.py#L42.

> If the file is truncated, it shouldn't be able to load the model, right?

I will conduct another test later. However, there is an interesting point to note. I just attempted to upload the same model to [narugo/xxx](https://huggingface.co/narugo/xxx/blob/main/anime_horn_v0_caformer_s36/model.onnx), and according to the page, this model has the same sha256 and size as the one that experienced consistency issues earlier. However, during the upload process, there was still an LFS upload step instead of directly reusing the file based on the same hash. Interestingly, this newly uploaded model, after testing, did not encounter the same error.

> About a quick fix for your issue, I would try to re-upload the corrupted file. If you try to re-upload exactly the same one it will not work because the Hub already think it has the same file on S3 (since we check based on file size/sha256 stored in git repo, not from S3). What you can do is to upload a slightly different file with the same name (for example, update just a metadata value inside it?)

I don't urgently need to use this model for now, so I will keep this situation as it is to assist you in investigating the issue further and implementing a comprehensive fix afterwards. I hope this can be helpful to you.

**Comment by narugo1992** [comment] 2023-06-21 10:55
I manually downloaded the model from [deepghs/anime_ch_horn](https://huggingface.co/deepghs/anime_ch_horn/blob/main/caformer_s36_v0/model.onnx) and attempted to run it locally (`huggingface_hub==0.15.1`). However, I encountered the following error:

```
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from /home/narugo/downloads/horn_model.onnx failed:Protobuf parsing failed.
```

I believe this indicates that the file is incomplete, which leads to the protobuf library reading incomplete data and causing this error.

**Comment by Wauplin** [comment] 2023-06-21 13:11
>  so I will keep this situation as it is to assist you in investigating the issue further and implementing a comprehensive fix afterwards. I hope this can be helpful to you.

> I believe this indicates that the file is incomplete, which leads to the protobuf library reading incomplete data and causing this error.

Thank you very much for your commitment! Confirming that the issue is indeed that the uploaded file is truncated is already a valuable information. What we need to understand now is why the commit has been completed while a LFS upload was not complete yet. Since it's not the first time it happens (see https://github.com/huggingface/huggingface_hub/issues/1445) I doubt this is a coincidence. 

A potential bug I suspect is if an LFS fails while running in a background thread and that the error is not propagated. I'll need to investigate that further to confirm it or not.

**Comment by narugo1992** [comment] 2023-06-28 04:55
> @narugo1992 getting back to it I am wondering if you're using `hf_transfer` in your upload scripts? (meaning having [hf_transfer](https://github.com/huggingface/hf_transfer) installed + [`HF_HUB_ENABLE_HF_TRANSFER=1`](https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hfhubenablehftransfer) as env variable). Knowing this would narrow down my research a bit :)

I'm quite certain that I haven't used `hf_transfer`, and I've checked the runtime environment to confirm that it hasn't been used either, nor have I configured the corresponding environment variables. In fact, I wasn't aware of the existence of this powerful library before, but I will keep an eye on its progress in the future :smiley:

**Comment by Wauplin** [comment] 2023-06-28 06:54
>  I've checked the runtime environment to confirm that it hasn't been used either, nor have I configured the corresponding environment variables

If you are running your code in a Space, hf_transfer is most likely enabled since we try to speed up transfers on our own infra. If you are running it somewhere else, there is no way it has been installed/enabled automatically :) And in your case it is a Github CI right?
So should be plain Python code without Rust bindings (which might make the debugging/finding the bug much easier)

**Comment by Wauplin** [comment] 2023-06-28 08:47
@narugo1992 Just to be sure, do you need something from me to solve your specific issue with the broken onnx file or do you already have a workaround? I'll keep this issue opened because I need to investigate further why an upload can fail in such a way but if you need further assistance on this specific issue, please let me know.

Also to let you know that we are working on adding a safe-guard server-side to check the uploaded file size before committing. This should prevent such cases in the future even if it doesn't repair existing corrupted files.

**Comment by narugo1992** [comment] 2023-06-28 11:10
Regarding the existing issue, it is indeed difficult for me to fine-tune the file to only make minor adjustments to avoid the hash check. This file is in the onnx format, and it is difficult to modify it without affecting its usability. Additionally, in some scenarios, this onnx file is still directly used, although such scenarios are few and not highly urgent. Therefore, if possible, I would prefer to have the hash record of this file cleared so that I can re-upload the complete version. Alternatively, copying [the file from `narugo/xxx` (which is identical to the complete version and has been tested for integrity)](https://huggingface.co/narugo/xxx/blob/main/anime_horn_v0_caformer_s36/model.onnx) to this location would also be acceptable. Thanks.

**Comment by Wauplin** [comment] 2023-06-28 11:22
@Pierrci @coyotte508 Regarding https://github.com/huggingface/huggingface_hub/issues/1521#issuecomment-1611211216, would it be possible to either:
- remove [this file](https://huggingface.co/deepghs/anime_ch_horn/blob/main/caformer_s36_v0/model.onnx) from S3 for this repo
- or copy the file [from this repo](https://huggingface.co/narugo/xxx/blob/main/anime_horn_v0_caformer_s36/model.onnx) to [this one](https://huggingface.co/deepghs/anime_ch_horn/blob/main/caformer_s36_v0/model.onnx) (should be identical) 

Current problem is that a corrupted file has been uploaded (partial upload only) but we can't upload it again as moon-landing "think" it already exists (see [related issue](https://github.com/huggingface/moon-landing/issues/5885#issuecomment-1609607516) in moon-landing).

**Comment by coyotte508** [comment] 2023-06-28 12:34
File was removed

**Comment by Wauplin** [comment] 2023-06-30 14:25
Thanks @coyotte508 for deleting the corrupted file. Thanks also [for this PR](https://github.com/huggingface/moon-landing/issues/5885) (internal link). @narugo1992 the server now rejects the commit if an LFS file has not been uploaded correctly. This means commit fails completely and the script has to be restarted completely. But at least we don't end up with a corrupted repo anymore.

```
huggingface_hub.utils._errors.BadRequestError:  (Request ID: 1251b384-ded1-49e4-b05c-6dbfec8cc308)

Bad request for commit endpoint:
Your push was rejected because an LFS pointer pointed to a file that does not exist. For instance, this can happen if you used git push --no-verify to push your changes. Offending file: - file_50MB.bin
```

I still don't know why we happened to have corrupted files but since it's not reproducible + we have the safe check server-side, I don't think it's worth investigating further.
=> I'll close this issue. @narugo1992 feel free to reopen if the issue is not completely addressed on your side.

**Closed by Wauplin** 2023-06-30 14:25 UTC
Labels: bug
