### ISSUE TITLE
hugging_face_cli login not working in WIndow

### ISSUE THREAD

**Issue by kurianbenoy-aot** [huggingface/huggingface_hub#696] opened 2022-02-21 10:21 UTC
**Is your feature request related to a problem? Please describe.**

On running the command: `huggingface-cli login`. I noticed that when I am passing a access token to login, I am frusturated with
this error message:

```
Traceback (most recent call last):
  File "C:\Users\Kurian Benoy\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Kurian Benoy\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\work\Sentiment-analysis-expts\venv\Scripts\huggingface-cli.exe\__main__.py", line 7, in <module>
  File "d:\work\sentiment-analysis-expts\venv\lib\site-packages\huggingface_hub\commands\huggingface_cli.py", line 41, in main
    service.run()
  File "d:\work\sentiment-analysis-expts\venv\lib\site-packages\huggingface_hub\commands\user.py", line 174, in run
    _login(self._api, token=token)
  File "d:\work\sentiment-analysis-expts\venv\lib\site-packages\huggingface_hub\commands\user.py", line 415, in _login
    hf_api.set_access_token(token)
  File "d:\work\sentiment-analysis-expts\venv\lib\site-packages\huggingface_hub\hf_api.py", line 489, in set_access_token
    write_to_credential_store(USERNAME_PLACEHOLDER, access_token)
  File "d:\work\sentiment-analysis-expts\venv\lib\site-packages\huggingface_hub\hf_api.py", line 344, in write_to_credential_store
    with subprocess.Popen(
  File "C:\Users\Kurian Benoy\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kurian Benoy\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**About System**

Python version: 3.9
Operating system: Windows 10

**Comment by LysandreJik** [comment] 2022-03-10 10:24
Hey @kurianbenoy-aot, tried to reproduce but didn't manage to. Could you share some information about your environment? i.e., what is your Python version, are you running it in the cmd shell, in wsl? Thank you!

**Comment by LysandreJik** [comment] 2022-03-10 10:35
I succeeded with the following:
- Install `huggingface_hub` through pypi's latest package or through the git source install
- Add the path in which the script was installed to `$PATH`
- Logged-in
- Verified it worked by importing `whoami` and verifying that the correct info was output

**Comment by adrinjalali** [comment] 2022-03-16 13:16
Closing as there seems to be a fix. Happy to reopen if it's still an issue @kurianbenoy-aot

**Closed by adrinjalali** 2022-03-16 13:16 UTC
