### ISSUE TITLE
[notebook_login] Error: Module @jupyter-widgets/controls, version ^1.5.0 is not registered, however, 2.0.0 is

### ISSUE THREAD

**Issue by 0xdevalias** [huggingface/huggingface_hub#1160] opened 2022-11-06 23:27 UTC
### Describe the bug

While using `dreambooth_colab_joepenna.ipynb` from https://github.com/JoePenna/Dreambooth-Stable-Diffusion/ on RunPod, there is a cell with the following code:

```
# Hugging Face Login
from huggingface_hub import notebook_login

notebook_login()
```

When running that cell, the following error is displayed:

```
Error: Module @jupyter-widgets/controls, version ^1.5.0 is not registered, however,         2.0.0 is
```
```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'VBoxModel' from module '@jupyter-widgets/controls'
Error: Module @jupyter-widgets/controls, version ^1.5.0 is not registered, however,         2.0.0 is
    at f.loadClass (https://REDACTED-REDACTED-8888.proxy.runpod.io/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:74977)
    at f.loadModelClass (https://REDACTED-REDACTED-8888.proxy.runpod.io/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:10729)
    at f._make_model (https://REDACTED-REDACTED-8888.proxy.runpod.io/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:7517)
    at f.new_model (https://REDACTED-REDACTED-8888.proxy.runpod.io/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:5137)
    at f.handle_comm_open (https://REDACTED-REDACTED-8888.proxy.runpod.io/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/150.3e1e5adfd821b9b96340.js?v=3e1e5adfd821b9b96340:1:3894)
    at _handleCommOpen (https://REDACTED-REDACTED-8888.proxy.runpod.io/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:73393)
    at b._handleCommOpen (https://REDACTED-REDACTED-8888.proxy.runpod.io/static/lab/jlab_core.e37d4bbc8c984154bc26.js?v=e37d4bbc8c984154bc26:2:1001251)
    at async b._handleMessage (https://REDACTED-REDACTED-8888.proxy.runpod.io/static/lab/jlab_core.e37d4bbc8c984154bc26.js?v=e37d4bbc8c984154bc26:2:1003241)
```

See also:

- https://github.com/JoePenna/Dreambooth-Stable-Diffusion/issues/42

### Reproduction

- Clone https://github.com/JoePenna/Dreambooth-Stable-Diffusion/
- Run `dreambooth_colab_joepenna.ipynb`
- Run each of the cells until you get to the 'Hugging Face Login' cell
- Run the 'Hugging Face Login' cell
- Observe the error

### Logs

```shell
See above
```

### System Info

```shell
!python --version
Python 3.10.8
```

```
Requirement already satisfied: huggingface_hub in /venv/lib/python3.10/site-packages (0.10.1)
```

```
JupyterLab Version 3.5.0
```
```

**Comment by Wauplin** [comment] 2022-11-07 09:47
Hello @0xdevalias :wave: Sorry you are experiencing this issue. I don't know where it comes from and haven't been able to reproduce it on my laptop. Could it be that it has to do with how JupyterLab is launched by RunPod ? (I'm suggesting this because of this workaround https://github.com/JoePenna/Dreambooth-Stable-Diffusion/issues/42#issuecomment-1272730151 :confused:)

---

That's said a possible workaround is to skip the widgets in the login phase. This has been implemented very recently and is therefore available only on the `main` branch and starting from next `hfh` release. The idea is to pass the token programmatically instead of requesting it to the user:

```py
# !pip install git+https://github.com/huggingface/huggingface_hub.git
from huggingface_hub import login

login(token="hf_***")
```

**Comment by 0xdevalias** [comment] 2022-11-07 09:55
> Could it be that it has to do with how JupyterLab is launched by RunPod ?

I'm not too sure tbh, i'm pretty new to notebooks/etc.

Based on the workaround, I did try refreshing the page and it seemed to work after that. I think one of the steps in the notebook was `pip` installing requirements, potentially including that one; so maybe it's just a case that it can't actually use those newly installed things properly without a refresh?

Good to know about the new programmatic login method, will definitely keep that in mind for future :)

**Comment by Wauplin** [comment] 2022-11-07 10:01
> I think one of the steps in the notebook was pip installing requirements, potentially including that one

Yep that's clearly the case. Not sure though how things are (re-)loaded after install. I'm quite inexperienced on these notebooks related matters as well and this seems really more a jupyter/ipywidget issue. 

Is it fine with you to close this issue as there is nothing much we can do for it in `huggingface_hub` ?

**Comment by 0xdevalias** [comment] 2022-11-07 10:12
Totally understandable.

Yeah, happy for you to close this :) At the very least now there'll be a copy of this error (and some potential workarounds) when someone (or myself) searches the issues again in future.

Thanks for your help 🖤

**Closed** 2022-11-07 10:13 UTC
Labels: bug
