### ISSUE TITLE
"batch response: Too many password attempts".can't push a lot of files.

### ISSUE THREAD

**Issue by AisingioroHao0** [huggingface/huggingface_hub#1584] opened 2023-08-11 08:37 UTC
### Describe the bug

Neither ```git push``` from the command line nor ```repo.push``` from python will work. I made sure that my cli was logged in and that my ssh public key had been added to my huggingfacehub account. I found that pushing a lot of files wouldn't work. In this example I tried to push around 3,000 files.

### Reproduction

```python
from huggingface_hub import Repository
repo = Repository(local_dir="/home/aihao/workspace/DeepLearningContent/datasets/images")
# repo.git_add(".")
# repo.git_commit(commit_message="add pixiv images")
repo.git_push()
```

### Logs

```shell
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
error: failed to push some refs to 'hf.co:datasets/AisingioroHao0/images'

Traceback (most recent call last):
  File "/home/aihao/miniconda3/envs/torch/lib/python3.11/site-packages/huggingface_hub/repository.py", line 1099, in git_push
    raise subprocess.CalledProcessError(return_code, process.args, output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'push']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aihao/workspace/DeepLearningContent/datasets/upload.py", line 5, in <module>
    repo.git_push()
  File "/home/aihao/miniconda3/envs/torch/lib/python3.11/site-packages/huggingface_hub/repository.py", line 1102, in git_push
    raise EnvironmentError(exc.stderr)
OSError: batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
batch response: Too many password attempts
error: failed to push some refs to 'hf.co:datasets/AisingioroHao0/images'
```

### System info

```shell
- huggingface_hub version: 0.16.4
- Platform: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- Python version: 3.11.3
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/aihao/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: AisingioroHao0
- Configured git credential helpers: store
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.0.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 9.4.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: N/A
- numpy: 1.24.3
- pydantic: 1.10.9
- aiohttp: 3.8.4
- ENDPOINT: https://huggingface.co
- HUGGINGFACE_HUB_CACHE: /home/aihao/.cache/huggingface/hub
- HUGGINGFACE_ASSETS_CACHE: /home/aihao/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/aihao/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
```

**Comment by Wauplin** [comment] 2023-08-11 09:17
@AisingioroHao0 I'm sorry you're experiencing this issue. I agree with you this use case is not very practical. We are trying to [get away from the local git commands](https://huggingface.co/docs/huggingface_hub/concepts/git_vs_http) and implement some HTTP methods instead that are more flexible to tweak for a use case like yours. Would you mind trying [`upload_file` or `upload_folder`](https://huggingface.co/docs/huggingface_hub/guides/upload#upload-a-file) and see if it solves your problem? You would most probably have to split your 3000 files in several commits (~100 files per commit?)

**Comment by AisingioroHao0** [comment] 2023-08-11 09:22
@Wauplin Sure. Let me try this api

**Comment by AisingioroHao0** [comment] 2023-08-11 09:56
@Wauplin 
I still run into some problems.
```python
from huggingface_hub import Repository
from huggingface_hub import HfApi

api = HfApi()
api.upload_folder(
    folder_path="/home/aihao/workspace/DeepLearningContent/datasets/images/data/x",
    path_in_repo="data",
    repo_id="aisingiorohao0/images",
    repo_type="dataset",
)
```
```
Traceback (most recent call last):
  File "/home/aihao/workspace/DeepLearningContent/datasets/upload.py", line 5, in <module>
    api.upload_folder(
  File "/home/aihao/miniconda3/envs/torch/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/aihao/miniconda3/envs/torch/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 828, in _inner
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aihao/miniconda3/envs/torch/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 3478, in upload_folder
    add_operations = _prepare_upload_folder_additions(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aihao/miniconda3/envs/torch/lib/python3.11/site-packages/huggingface_hub/hf_api.py", line 5075, in _prepare_upload_folder_additions
    for path in sorted(folder_path.glob("**/*"))  # sorted to be deterministic
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aihao/miniconda3/envs/torch/lib/python3.11/pathlib.py", line 953, in glob
    for p in selector.select_from(self):
  File "/home/aihao/miniconda3/envs/torch/lib/python3.11/pathlib.py", line 408, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "/home/aihao/miniconda3/envs/torch/lib/python3.11/pathlib.py", line 356, in _select_from
    entries = list(scandir_it)
              ^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error: '/mnt/d/workspace/DeepLearningContent/datasets/images/data/pixiv/x/y'
```
Is the path too long?

**Comment by AisingioroHao0** [comment] 2023-08-11 10:27
只有几个文件夹不行，奇怪。例如```/mnt/d/workspace/DeepLearningContent/datasets/images/data/pixiv/MISSILE228/Illustration```

**Comment by Wauplin** [comment] 2023-08-17 10:29
Hey @AisingioroHao0, I looked a bit into your error and it doesn't seem to be related to `huggingface_hub` itself. Could it be related to [this issue](https://github.com/borgbackup/borg/issues/5974). The OSError related to WSL2 + mounted path seems very similar to your problem. Can't really help with that to be honest since it's `Path.glob("*")` that is failing and `huggingface_hub` can't know which files to upload if it cannot scan your directory.

A workaround could be to provide the list of files yourself and use [`create_commit`](https://huggingface.co/docs/huggingface_hub/guides/upload#createcommit). It's not ideal but it might unblock you for this specific problem (without solving the root cause).

**Comment by Wauplin** [comment] 2023-08-17 14:34
Good to hear! I'm closing this issue then :)

**Closed by Wauplin** 2023-08-17 14:34 UTC
Labels: bug
