### ISSUE TITLE
Resolving pain-points for uploading large files and folders

### ISSUE THREAD

**Issue by sleepingcat4** [huggingface/huggingface_hub#2612] opened 2024-10-16 18:22 UTC
I wanted to share the pain-points I've faced for the past 2 months while I was busy uploading 3TB worth datasets. Below are the pain-points:

1. HF limits itself to 50GB load. I'm okay with that but if a file is 49GB **showed by du -h command on ubuntu**, HF detects it as 50 exceed load and refuses to upload. 
2. HF upload folder method works fine as long as I have less than 1000 files inside my folder. If number exceeds more than 1000, HF will start showing me different errors. Such as it either does not detect all the files inside the folder (some are a few kb) or AWS bucket error happens (probably backend error). (I'm aware of multi-commit but this if I've less than 2000 files that's worth less than 400GB, I believe it should handle it in a single commit)
3. Unable to read error messages. HF has a way of gracefully handling the errors. I appreciate the thoughtfulness but sometimes it's complete necessary. Because I'm uploading tons of data and if something goes wrong (for example parquet files schema error) it should be able to tell me than saying a generic message. 
4. There's no force building option once I change README for a large repository
5. It will make life a breeze if HF made more examples and listed out all the ways we can create subset (for folders), for files and etc. Because right now all the docs are spread across and for some cases, I have to test and try. 
6. If I use upload_folder function, I expected my files will be inside uploaded from local folder to another folder inside the main branch. Rather it gets uploaded as single files in the main branch. making it hard for me to find other files on the main branch that are not related to the dataset (as data). 

resolving these pain-points would make life too easy : ) I understand these sentiments is hard to share unless someone actively uploads large loads on HF. But, this make life too relaxing and easy to upload datasets.

**Comment by Wauplin** [comment] 2024-10-17 09:19
Hi @sleepingcat4, thanks for your feedback. I'll try to address your comments one by one.

> HF limits itself to 50GB load. I'm okay with that but if a file is 49GB showed by du -h command on ubuntu, HF detects it as 50 exceed load and refuses to upload.

I supposed this is because of a difference between GiB and GB. 50GB ~= 46,6GiB. Can that be the cause of your problem?
If you create a file of exactly 1e9 bytes (`open("test_1GB", "wb").write(b"0"*1e9)`), and do a `du -h`, you'll get **954M** not **1G**. You should therefore try to reduce files sizes. 

>  Such as it either does not detect all the files inside the folder (some are a few kb)

I'd be interested if you have a reproducible example. Detection is not based on the file size, we are just doing a glob(*).

> I'm aware of multi-commit but this if I've less than 2000 files that's worth less than 400GB, I believe it should handle it in a single commit

Actually a 2000 files/400GB commit is enormous so I'm not surprised if it cannot be handled in a single commit.
The problem is not really the file size but the number of files. When you create a commit with an LFS file, the server has to check that the file you point to and the reference in the commit are consistent. It requires an extra call on the backend between our server and S3. Doing this 2000 times can take a significant amount of time. Since we don't have transactional commits and that any request to the Hub has a 60s timeout (i.e. after 60s of process, the request is cancelled server-side), then you get an error.

In fact, `upload_folder` is not meant to be used on very large folders. It works best for a few dozens of files at most but that's all. For larger uploads, we recommend using a dedicated `upload_large_folder` command which ends-up creating multiple commits but at least the process is resumable and fault-tolerant. More details here: https://huggingface.co/docs/huggingface_hub/guides/upload#upload-a-large-folder

> Because I'm uploading tons of data and if something goes wrong (for example parquet files schema error) it should be able to tell me than saying a generic message.

I suspect you are referring to the `datasets` library here. In `huggingface_hub` itself, we don't check any consistency in the files that are uploaded. The library is agnostic of any file structure -expect maybe for the readme-.

> There's no force building option once I change README for a large repository

Not sure to understand this one. Are you referring to the dataset viewer? 

> It will make life a breeze if HF made more examples and listed out all the ways we can create subset (for folders), for files and etc. Because right now all the docs are spread across and for some cases, I have to test and try.

Are you referring specifically to datasets and the dataset viewer? If yes, this is unrelated to the file upload issues described in this issue. Better to open a separate issue in `datasets`  (for instance) to report feedback.

> If I use upload_folder function, I expected my files will be inside uploaded from local folder to another folder inside the main branch. Rather it gets uploaded as single files in the main branch. making it hard for me to find other files on the main branch that are not related to the dataset (as data).

When using `upload_folder`, you can pass `path_in_repo` to address exactly what you mention here. By default it's the root of the repo but you can define subfolders if you want. 
More details [here](https://huggingface.co/docs/huggingface_hub/v0.26.0.rc0/en/package_reference/hf_api#huggingface_hub.HfApi.upload_folder.path_in_repo).


Hope this addresses a bit your pain-points :hugs:

**Comment by julien-c** [comment] 2024-10-17 11:12
> I supposed this is because of a difference between GiB and GB.

I suggest always using the `--si` flag in `du`:
```
       --si   like -h, but use powers of 1000 not 1024
```

**Comment by sleepingcat4** [comment] 2024-10-18 07:15
> I'd be interested if you have a reproducible example. Detection is not based on the file size, we are just doing a glob(*).

Unfortunately, I don't have an example at the moment but when I was trying to upload 2000 files (400GB load) on HF, during one of the attempts, it showed to upload only 723 files whereas I had 2000 files. 

I had a feature (maybe this already exists) in mind. I read through different HF documentation but I didn't receive a clear answer if it was possible. If I have a folder (1.5TB), I zip it and then upload the folder in the form of shards. Like divide zip file based on its bytes into 50GiB sub portions and upload them. And when a user downloads the dataset and saves on disk, HF datasets module can automatically join the sub-portions into creating the complete zip file. 

I tried this method on single files but never tried to apply on zipped folders. But, if this feature can be implemented uploading large files in one shot with multiple commits for each sub-files will become a breeze, without the me/uploader needing to take care of diving and anything else. 

**some of the pain-points are overlapped with datasets repo, sorry for not noticing earlier. I will try to create a feature request there for them.** And thank you for the helpful reply.

**Comment by Wauplin** [comment] 2024-10-18 08:34
> Unfortunately, I don't have an example at the moment but when I was trying to upload 2000 files (400GB load) on HF, during one of the attempts, it showed to upload only 723 files whereas I had 2000 files.

What most probably happened is that out of the 2000 files, only 723 of them were LFS files? And since LFS files are preuploaded before the commit, we show a progress bar for them.

**Comment by Wauplin** [comment] 2024-10-18 08:40
> I had a feature (maybe this already exists) in mind. I read through different HF documentation but I didn't receive a clear answer if it was possible. If I have a folder (1.5TB), I zip it and then upload the folder in the form of shards. Like divide zip file based on its bytes into 50GiB sub portions and upload them. And when a user downloads the dataset and saves on disk, HF datasets module can automatically join the sub-portions into creating the complete zip file.

> I tried this method on single files but never tried to apply on zipped folders. But, if this feature can be implemented uploading large files in one shot with multiple commits for each sub-files will become a breeze, without the me/uploader needing to take care of diving and anything else.

In general, it's always best to upload without zipping otherwise users have to download the full dataset in order to check whether the data it contains is useful for them (whereas if unzipped files are uploaded, one can just download a subset of the dataset). 

On another topic, we are currently working on a rework of our storage backend to facilitate upload of very large files / models / datasets. Here was our announcement blog post: https://huggingface.co/blog/xethub-joins-hf. We'll share more once when the time comes!

**Comment by Wauplin** [comment] 2024-10-18 08:41
I think we've addressed all the points mentioned above so I'll close this issue (as well as https://github.com/huggingface/huggingface_hub/issues/2577 which is related).

**Closed by Wauplin** 2024-10-18 08:41 UTC
