### ISSUE TITLE
list_datasets() different result from HF Datasets

### ISSUE THREAD

**Issue by onadegibert** [huggingface/huggingface_hub#1351] opened 2023-02-17 15:32 UTC
### Describe the bug

Hi there,

I am not sure if this is a bug.

I am just trying to search the hub using these commands:

```
from huggingface_hub import HfApi

api = HfApi()

datasets = api.list_datasets(sort="downloads")

print(len(datasets))
```

I am getting over 46k datasets, while on the actual hub I can only see 21,778. Why is there such a huge difference in terms of available datasets?

Thanks!

### Steps to reproduce the bug

```
from huggingface_hub import HfApi

api = HfApi()

datasets = api.list_datasets(sort="downloads")

print(len(datasets))
```

### Expected behavior

It should print the same number as in the Hugging face hub: 21777

### Environment info

huggingface-hub==0.12.1

**Comment by Wauplin** [comment] 2023-02-20 09:13
(thanks @albertvillanova for transferring :) )

Hi @onadegibert, thank you for reporting this issue. I have been able to reproduce it myself.
Seems to be a server-side issue so [I reported it internally](https://github.com/huggingface/moon-landing/issues/5430#issuecomment-1436596718). I'll keep this issue open to keep you posted about the fix.

For the record, `list_datasets` has duplicates when used with `sort="downloads"` (not the case without sorting). The problem is not that we list private datasets that you don't have access to.

**Comment by Wauplin** [comment] 2023-02-23 17:39
@onadegibert  The issue has been fixed server-side thanks to @Kakulukian and @coyotte508  :pray: 

So now you can sort your datasets as expected:
```py
print(len(list_datasets()))  # 22k
print(len(list_datasets(sort="downloads")))  # 22k
print(len(list_datasets(sort="lastModified")))  # 22k
```
You might not get the exact number when sorting by `downloads` (for caching reason, new datasets that have not been downloaded once are not listing). Should be fixed separately later as it's a less problematic issue.

**Closed** 2023-02-23 17:40 UTC
