### ISSUE TITLE
Better error message on 401

### ISSUE THREAD

**Issue by coyotte508** [huggingface/huggingface_hub#1124] opened 2022-10-19 20:20 UTC
Context: https://huggingface.slack.com/archives/C02EMARJ65P/p1666209273786889

Let's display the actual content of the error from the HTTP response, like we already in other places, for 401? It would show the message that the token is expired to the user.

**Comment by Wauplin** [comment] 2022-10-20 10:00
*(copy-pasting from internal thread):*

**Category:**
Hub auth & account mgmt

**Details:**
the hub's machinery fails to indicate
the token has expired and keeps the user logged in or let's the user login with an expired token. but then at run time it fails and it's impossible to tell why it gets 401 for public models.
This possibly has to do with the god token.
Also note it lets me log in with an expired token w/o giving me any error. and then it fails to work at run time.
```
python -c 'from transformers import AutoModel; AutoModel.from_pretrained("HuggingFaceM4/tiny-model_tr_32")'
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/py38-pt112/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 213, in hf_raise_for_status
    response.raise_for_status()
  File "/home/stas/anaconda3/envs/py38-pt112/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/HuggingFaceM4/tiny-model_tr_32/resolve/main/config.json
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/mnt/nvme0/code/huggingface/transformers-master/src/transformers/utils/hub.py", line 409, in cached_file
    resolved_file = hf_hub_download(
  File "/home/stas/anaconda3/envs/py38-pt112/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1053, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/home/stas/anaconda3/envs/py38-pt112/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 1359, in get_hf_file_metadata
    hf_raise_for_status(r)
  File "/home/stas/anaconda3/envs/py38-pt112/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 242, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: r-XP0U-5zIDWGze4UdY6n)
Repository Not Found for url: https://huggingface.co/HuggingFaceM4/tiny-model_tr_32/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If the repo is private, make sure you are authenticated.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/nvme0/code/huggingface/transformers-master/src/transformers/models/auto/auto_factory.py", line 434, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/mnt/nvme0/code/huggingface/transformers-master/src/transformers/models/auto/configuration_auto.py", line 773, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/mnt/nvme0/code/huggingface/transformers-master/src/transformers/configuration_utils.py", line 558, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/mnt/nvme0/code/huggingface/transformers-master/src/transformers/configuration_utils.py", line 613, in _get_config_dict
    resolved_config_file = cached_file(
  File "/mnt/nvme0/code/huggingface/transformers-master/src/transformers/utils/hub.py", line 424, in cached_file
    raise EnvironmentError(
OSError: HuggingFaceM4/tiny-model_tr_32 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
```

**Comment by Wauplin** [comment] 2022-10-20 10:19
@stas00 I tried with normal tokens and it works as expected. E.g: if you try to login with a valid token, it works. If you invalidate this token from [the settings page](https://huggingface.co/settings/tokens), next requests to private models will fail with HTTP 401. And finally if you try to login (`huggingface-cli login`) with a token that you invalidated from the settings page, it will refuse it (`ValueError: Invalid token passed!`).

About god tokens, I am not sure that we want to adapt `hfh` specifically to them as they are not meant to exist publicly. I personally don't have one so I cannot reproduce your issue. In general, I'd be fine if the server returns an error message like `Token is outdated. Please use a new one.` but this has to be done in `moon-landing` instead of `hfh`. (still has to be discussed, I'm not even sure outdated tokens are still stored somewhere).

About the error message returned from the server on a HTTP 401, it should be automatically displayed to the user by `hfh` but `moon-landing` doesn't seem to return something.

```
from huggingface_hub import model_info

model_info("Wauplin/dummy_private")

# inside debugger:
# print(response.json())
# => {'error': ''}
```

There is a `"X-Error-Code"` header sometimes that we use to determine which error type it is (can be `RevisionNotFound`, `EntryNotFound` or `RepoNotFound`) but that's orthogonal.

**Comment by stas00** [comment] 2022-10-20 15:43
I don't have a particular attachment to how this should be, as long as there is a clear indication in the error that the token is expired. I wasted quite a few hours puzzling over and trying to fix the software and being forced to add the auth token to public models/datasets download as they refused to download. So it's a serious problem.

Then I tried to logout and login again and that operation worked just fine, I still had no idea the token was expired. My code still wasn't working.

I then started asking others if they have the same problem, and they said my code worked for them just fine, but not for me.

Only once I went to the tokens page I have finally noticed the token was expired and then solved the problem.

**Comment by Wauplin** [comment] 2022-10-21 13:48
@stas00 part of the problem has been solved by https://github.com/huggingface/huggingface_hub/pull/1121. See [slack message](https://huggingface.slack.com/archives/C03V11RNS7P/p1666359844856729?thread_ts=1666267566.885549&cid=C03V11RNS7P) (internal link).
Also 2 other related issues created on `moon-landing`: https://github.com/huggingface/moon-landing/issues/4214 and https://github.com/huggingface/moon-landing/issues/4216 (internal links).

Therefore, I'm closing this issue as resolved :)

**Closed by Wauplin** 2022-10-21 13:48 UTC
