### ISSUE TITLE
Network connection error prevent use of a cached download

### ISSUE THREAD

**Issue by howff** [huggingface/huggingface_hub#1099] opened 2022-10-06 21:33 UTC
When a network connection is not available an exception is rasied inside `cached_download()`:

https://github.com/huggingface/huggingface_hub/blob/af1d49e9eed3b31be86652cfcfdae9bfba4f3814/src/huggingface_hub/file_download.py#L639

Surely it should check for a previously cached download and return that, isn't that the whole point of the `cached_download` function?

**Comment by julien-c** [comment] 2022-10-12 09:50
maybe to raise on MITM attacks? 

There is probably more context in the `transformers` repo history because this was extracted from there i think. Look for something like `do not gobble certain kinds of requests.ConnectionError ` or something. cc @LysandreJik

**Comment by LysandreJik** [comment] 2022-10-12 21:25
From PR https://github.com/huggingface/transformers/pull/10235

I looked for more context internally but didn't find some.

**Comment by julien-c** [comment] 2022-10-13 19:51
yes so here is the actual context: https://github.com/huggingface/transformers/issues/8690#issuecomment-777781446

And indeed we wanted to raise on proxy or SSL errors because this is usually developer-error (proxy setup issue) i.e. it's not a ConnectionError (the OP description is incorrect in that regard)

**Comment by julien-c** [comment] 2022-10-13 19:52
@howff ok if we close this as this is the intended behavior?

**Comment by howff** [comment] 2022-10-13 21:30
Sorry, I prefer this to be fixed rather than closed, because I need to use pre-cached models inside an environment that has no Internet access or a proxy which blocks most sites.

**Comment by LysandreJik** [comment] 2022-10-13 22:52
In `transformers`, we handle that by having a specific environment variable (`TRANSFORMERS_OFFLINE`) which allows using all previously downloaded files without doing any calls to check if they've been updated.

There is a `HF_HUB_OFFLINE` here which should/could behave the same but I'm don't think it's supported @Wauplin?

**Comment by Wauplin** [comment] 2022-10-14 09:15
@howff  `HF_HUB_OFFLINE=1` is indeed the way to go for your use case (thanks @LysandreJik to point this :pray: )

Here is a small test script:

```py
# download.py
from huggingface_hub import cached_download, hf_hub_download

print("With `cached_download` (deprecated)")
print(cached_download("https://huggingface.co/gpt2/blob/main/config.json"))

print("\nWith `hf_hub_download` (preferred)")
print(hf_hub_download(repo_id="gpt2", filename="config.json"))
```

And here is the result:
```sh
# Run once to cache the files
 ➜ python download.py
With `cached_download` (deprecated)
/home/wauplin/projects/huggingface_hub/src/huggingface_hub/file_download.py:588: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  warnings.warn(
/home/wauplin/.cache/huggingface/hub/32ced3a9285c2335a2cebda8f31de1554afda9139b7aca822498b4cfd2de5921.dd2196627193cbe5003d6f5943d141946baa2e01534cd8533176541bc777da45

With `hf_hub_download` (preferred)
/home/wauplin/.cache/huggingface/hub/models--gpt2/snapshots/909a290700bd99135e67c64eefc166960b67cfd2/config.json
 
 # Run a second time in offline mode (to run where your internet access is limited)
 ➜ HF_HUB_OFFLINE=1 python download.py 
With `cached_download` (deprecated)
/home/wauplin/projects/huggingface_hub/src/huggingface_hub/file_download.py:588: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  warnings.warn(
/home/wauplin/.cache/huggingface/hub/32ced3a9285c2335a2cebda8f31de1554afda9139b7aca822498b4cfd2de5921.dd2196627193cbe5003d6f5943d141946baa2e01534cd8533176541bc777da45

With `hf_hub_download` (preferred)
/home/wauplin/.cache/huggingface/hub/models--gpt2/snapshots/909a290700bd99135e67c64eefc166960b67cfd2/config.json
```

Does that solve your problem ? :)

**Comment by howff** [comment] 2022-10-18 21:33
Thank you very much, `HF_HUB_OFFLINE=1` does indeed solve my problem :-)

Personally I still think that a function which is intended to return a cached file (i.e. not use the internet) shouldn't fail when the internet is not available.

**Comment by julien-c** [comment] 2022-10-19 07:59
> Personally I still think that a function which is intended to return a cached file (i.e. not use the internet) shouldn't fail when the internet is not available.

As mentioned before, that is the case (ConnectionErrors are caught). What is not caught is SSLError and ProxyError, e.g. MITMs

**Comment by Wauplin** [comment] 2022-10-26 14:16
I am closing this issue as the problem is clearly identified and is caused on purpose as highlighted in https://github.com/huggingface/huggingface_hub/issues/1099#issuecomment-1283589478.

**Closed by Wauplin** 2022-10-26 14:16 UTC
