### ISSUE TITLE
Support non-blocking push with non-git methods

### ISSUE THREAD

**Issue by osanseviero** [huggingface/huggingface_hub#939] opened 2022-07-05 13:52 UTC
Some of the libraries, such as Transformers and diffusers, use a non-blocking push during training (see https://github.com/huggingface/diffusers/blob/main/src/diffusers/hub_utils.py#L92). They can't migrate to the non-git-based methods without deprecating that functionality. Would it be interesting to support non-blocking push?

cc @SBrandeis @julien-c @LysandreJik 

(from discussion with Simon it might require significant work so it might not be worth it)

**Comment by LysandreJik** [comment] 2022-07-05 14:20
Interesting! I'm reworking the push_to_hub here: https://github.com/huggingface/huggingface_hub/pull/847

It will be in the next release (v0.9). It leverages non-git-based methods. I can definitely add a non-blocking parameter and handle it in that method directly.

**Comment by Wauplin** [comment] 2022-08-09 08:38
Hey, I just discovered this issue related to https://github.com/huggingface/huggingface_hub/pull/847. As an update, the non-git `push_to_hub` is now in a review state and I did not take into account this feature request (I haven't seen it before 👀 ).

Given the 👍 and ❤️ on @LysandreJik 's message, it seems to be a quite expected feature. I would suggest that we address it in a separate PR coming just after the https://github.com/huggingface/huggingface_hub/pull/847 one.

---
That said, we can already discuss how the API would look like. I looked into the Repository code and it seems that when using `blocking=True`, push_to_hub will block and return a url (`str`). When using `blocking=False`, it returns a tuple `(str, CommandInProgress)`. First value is the same while `CommandInProcess` is a wrapper around the subprocess that is launched (`git push ...`).

To reproduce a similar pattern for HTTP endpoints (push_to_hub, upload_folder,...) I see multiple solutions with their pro and cons. As a comparison, here is the basic blocking version that we currently have:

```py
# Blocking by default !
model = MyModel()
commit_url = push_to_hub_keras(model, repo_id="Jikiwa/my-new-keras-model")
```

And disclaimer: I feel really bad at finding good names for objects/methods. Any suggestions here are more than welcomed.

### Solution 1: thread-based, similar to `CommandInProcess` and directly in `push_to_hub`

We can imagine a class similar to `CommandInProcess` but that would wrap around a thread. When using `blocking=False`, the function returns a `PushInProgress` object instead of a url. It has properties to get thread status and a `.join()` method to get the result (blocking step if thread was not ended yet). The class would also need to propagate exception nicely.

```py
model = MyModel()
push_in_progress = push_to_hub_keras(model, repo_id="Jikiwa/my-new-keras-model", blocking=False)
(...)
# Similar properties as for `CommandInProcess`
push_in_progress.status (.failed, .is_done,...)
# Blocking method to get result
commit_url = push_in_progress.join()
```

**Note:** it is not possible to return the `commit_url` without waiting for the push to complete since it will depend on the Hub response (especially if PR is created).

**Pros:**
- Seems to be as close as possible at what already exists for `Repository`
- Blocking functionality is directly mentioned in docstring with the argument
- Ease of use ?

**Cons:**
- `push_to_hub_keras` and all other HTTP-based functions have to updated to add the `blocking=False` option
- HTTP-based functions return type will not be consistent, sometimes returning a string, sometimes a Thread depending on the arguments. Maybe I'm too opinionated on typing but it doesn't feel so right to me.
- Threads are created for each push

### Solution 2: thread-based but in an helper

Instead of having a `blocking=False` argument in each HTTP endpoint, we could have a separate helper for it.

```py
model = MyModel()
push_in_progress = run_in_background(
      push_to_hub_keras,
      model,
      repo_id="Jikiwa/my-new-keras-model"
)
```

**Pros:**
- Same helper can be use with any of the existing and future http-based functions without additional overhead (no chances to forget it, no duplicated code)
- http-based functions will be independent from the "in_background" implementation:  
  - return types will be consistent
  - unittesting the helper itself would also be easier (more self-contained)
  
 **Cons:**
 - Maybe not as straightforward as using an argument
 - Threads are still created for each push
 - Is such a helper really specific to `huggingface_hub` ?

### Solution 2.5: a mix between both solutions

We can still have this helper and using `blocking=False` would just be way to automatically say "use `run_in_background` helper). This example is more implementation-related:

```py
def push_to_hub_keras(
    ...,
    blocking: bool = True,
) -> Union[str, PushInProgress]:
    if not blocking:
        return run_in_background(push_to_hub_keras, *args, **kwargs, blocking=False)
        
    (....)
```

**Pros:**
- Same API as in solution 1. Actually this is how I would implement solution 1.
- Not too much duplicated code
  
 **Cons:**
 - Still a bit of overhead for each function + return type consistency

### Solution 3: with `asyncio` and coroutines

I'm mentioning this possibility because IMHO this is typically the type of problem that could be solved using `asyncio` coroutines. I feel that going for the `asyncio` path is a bigger decision than just solving the non-blocking issue so I'm mentioning it but not really expecting us to implement it right now.

**Pros:**
- Coroutine is a pure-python feature. Users will not have to learn how our ad-hoc `PushInProgress` works.
- We don't use threads everywhere. Coroutines are more tight to python work (more memory and time-efficient, spawn as much as we want).
  
 **Cons:**
 - Implies a lot more refactoring:
   - Biggest problem of asyncio is that functions have to be defined in both `sync` and `async` versions. It is possible to have an "full async" client and then the "full sync" client would just be a wrapper around it, executing and waiting for the coroutines. 
   - All our code implementation is synced `requests`-based. We would have to switch to `httpx` which offer similar features.
   - Potentially implies more tests to write.
- We must assure API doesn't change for existing users.

---
(cc @LysandreJik @osanseviero @SBrandeis @anton-l for opinions)

**Comment by julien-c** [comment] 2022-08-09 08:44
+1 from me on handling this use case later, IF it's still necessary (it feels a little bit complex to me)

**Comment by osanseviero** [comment] 2022-08-09 11:45
+1 on separate PR. I do think it is quite useful as if we want to do pushes in `transformers` every n epochs (or in a `Callback` in `skops` or the Keras mixin, `diffusers`, etc) while training it will be a bottleneck to have to wait for the upload to be finished

**Comment by LysandreJik** [comment] 2022-08-10 06:57
In `transformers` we'll likely stay with the `Repository` approach that uses git. This is a use-case where the git workflow is favored as many operations are done and it's coherent to have a git repository evolve alongside the training.

This is the conclusion of the discussion that happened in https://github.com/huggingface/huggingface_hub/pull/321:
- Have git workflows for trainings and other workflows where it makes sense
- Have non-git workflows in situations where you just need to quickly push the weights

Considering this, I think having a non-blocking `push_to_hub` still has some value but isn't as vital as having a non-blocking `Repository`.

I would be perfectly fine with choosing to implement it only later if we see some workflows could drastically be improved by having non-git workflows, and thus require the non-blocking approach

---

I would favor option 1 of your proposals, @Wauplin, simply because it's very coherent with what we already have. Processes are already created for each non-blocking repository push so we have some knowledge of how to handle this the best.

**Comment by Wauplin** [comment] 2023-05-19 09:49
Issue has been solved by https://github.com/huggingface/huggingface_hub/pull/1458. 

Example of how it works:
```py
>>> from huggingface_hub import HfApi
>>> api = HfApi()
>>> api.run_as_future(api.create_repo, "username/my-model", exists_ok=True)
Future(...)
>>> api.upload_file(
...     repo_id="username/my-model",
...     path_in_repo="file.txt",
...     path_or_fileobj=b"file content",
...     run_as_future=True,
... )
Future(...)
```

Use `HfApi.run_as_future(...)` or directly `upload_file(..., run_as_future=True)`. The `run_as_future: bool` parameter is only available for the long-running commit tasks (i.e. `create_commit`, `upload_file`, `upload_folder`)

**Closed** 2023-05-26 09:17 UTC
Labels: discussion
