### ISSUE TITLE
Connection error with 0.20.1

### ISSUE THREAD

**Issue by alex-hh** [huggingface/huggingface_hub#1932] opened 2023-12-20 23:58 UTC
### Describe the bug

I experienced issues when upgrading from 0.19.4 to 0.20.1.

In particular datasets.load_dataset(<repo_name>, data_files=<filename>) throws the following exception in 0.20.1, but works fine when running exactly the same code in 0.19.4

```bash
ConnectionError: Couldn't reach https://huggingface.co/datasets/.../README.md (ConnectionError('Unauthorized for URL https://huggingface.co/datasets/.../README.md. Please use the parameter `token=True` after logging in with `huggingface-cli login`'))
```

Setting token=True, I get:

```bash
ConnectionError: Couldn't reach https://huggingface.co/datasets/.../README.md (error 401)
```

### Reproduction

datasets.load_dataset(<repo_name>, data_files=<filename>)

### Logs

```shell
ConnectionError: Couldn't reach https://huggingface.co/datasets/.../README.md (ConnectionError('Unauthorized for URL https://huggingface.co/datasets/.../README.md. Please use the parameter `token=True` after logging in with `huggingface-cli login`'))
```

### System info

```shell
- huggingface_hub version: 0.20.1
- Platform: Linux-6.2.0-39-generic-x86_64-with-glibc2.35
- Python version: 3.10.12
- Running in iPython ?: No
- Running in notebook ?: No
- Running in Google Colab ?: No
- Token path ?: /home/<machinename>/.cache/huggingface/token
- Has saved token ?: True
- Who am I ?: <username>
- Configured git credential helpers: store
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.1.1
- Jinja2: 3.1.2
- Graphviz: N/A
- Pydot: N/A
- Pillow: 10.1.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: 2.6.2.2
- numpy: 1.26.2
- pydantic: N/A
- aiohttp: 3.9.0
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: /home/<machinename>/.cache/huggingface/hub
- HF_ASSETS_CACHE: /home/<machinename>/.cache/huggingface/assets
- HF_TOKEN_PATH: /home/<machinename>/.cache/huggingface/token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment] 2023-12-21 12:56
Hi @alex-hh, thanks for reporting this issue. Just to be sure, which version of `datasets` are you using? Also, you could copy-paste the full stacktrace and the snippet of code that leads to this error? If you don't want to show which repo dataset you are trying to access, can you still report if it's a public, gated or private repo? Thank you in advance.

**Comment by alex-hh** [comment] 2023-12-21 15:38
Hi @Wauplin thanks for the response.

I'm using datasets 2.15.0. And accessing a private repository. When I try to pull the same file from a public repository with a similar data structure, I don't get the error with either huggingface_hub library version.

When using 0.19.4 I get this warning:

```bash
/home/instadeep56uk/alfred/venv/lib/python3.10/site-packages/huggingface_hub/repocard.py:105: UserWarning: Repo card metadata block was not found. Setting CardData to empty.
  warnings.warn("Repo card metadata block was not found. Setting CardData to empty.")
```
When using 0.20.1 I just get the error message above.

**Comment by alex-hh** [comment] 2023-12-21 16:45
raceback (most recent call last):
  File "/home/alexhh/alfred/test_hub.py", line 19, in <module>
    load_gym_dataset(DMS_name)
  File "/home/alexhh/alfred/test_hub.py", line 7, in load_gym_dataset
    return datasets.load_dataset(
  File "/home/alexhh/alfred/venv/lib/python3.10/site-packages/datasets/load.py", line 2128, in load_dataset
    builder_instance = load_dataset_builder(
  File "/home/alexhh/alfred/venv/lib/python3.10/site-packages/datasets/load.py", line 1814, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/home/alexhh/alfred/venv/lib/python3.10/site-packages/datasets/load.py", line 1511, in dataset_module_factory
    raise e1 from None
  File "/home/alexhh/alfred/venv/lib/python3.10/site-packages/datasets/load.py", line 1495, in dataset_module_factory
    ).get_module()
  File "/home/alexhh/alfred/venv/lib/python3.10/site-packages/datasets/load.py", line 1030, in get_module
    dataset_readme_path = cached_path(
  File "/home/alexhh/alfred/venv/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 182, in cached_path
    output_path = get_from_cache(
  File "/home/alexhh/alfred/venv/lib/python3.10/site-packages/datasets/utils/file_utils.py", line 599, in get_from_cache
    raise ConnectionError(f"Couldn't reach {url} ({repr(head_error)})")
ConnectionError: Couldn't reach https://huggingface.co/datasets/<repo_name>/resolve/819fa85d06b47235b8a66a288eef7803e538bb5d/README.md (ConnectionError('Unauthorized for URL https://huggingface.co/datasets/<repo_name>/resolve/819fa85d06b47235b8a66a288eef7803e538bb5d/README.md. Please use the parameter `token=True` after logging in with `huggingface-cli login`'))

**Comment by Wauplin** [comment] 2023-12-21 16:48
Thanks! Will have a look and get back to you :)

**Comment by Wauplin** [comment] 2023-12-22 10:22
Ping @lhoestq would you know when such an error is raised?
As far as I understand it looks like an authentication issue but I don't see what changes in `huggingface_hub` that could have produced this issue. We started to -slowly- deprecate `HfFolder.get_token` but the code implementation did not change at all. Also the bug fix pushed to `datasets` (but not released yet) to comply with 0.20.1 was only fixing warning messages, not the behavior itself. So maybe it's completely something else and I don't see it.

For the record I've tried to reproduce the issue with no success. @alex-hh maybe you could share what the format structure of the dataset is? Or even better, create a reproducible dataset example with dummy data for which you get this error when the dataset is in private but not when it's public. That would help a lot solving the idea.

**Comment by lhoestq** [comment] 2023-12-22 11:19
`datasets` uses HfFolder.get_token in get_authentication_headers_for_url()

Can you try logging in again @alex-hh ?
```
huggingface-cli login
```

**Comment by alex-hh** [comment] 2023-12-22 11:53
Thanks both for investigating. Logging back in appears to have resolved the issue (now confused about what was going wrong yesterday as thought I had tried this). Thanks!

**Comment by Wauplin** [comment] 2023-12-22 12:33
Glad to know your issue has been resolved! :tada: 
I'm closing this issue then :)

**Closed by Wauplin** 2023-12-22 12:33 UTC
Labels: bug
