### ISSUE TITLE
OSError: Consistency check failed

### ISSUE THREAD

**Issue by Craig-Dornan** [huggingface/huggingface_hub#2520] opened 2024-09-06 14:17 UTC
### Describe the bug

OSError: Consistency check failed: file should be of size 440449768 but has size 2288622 ((…)VmwASYFDempA__&Key-Pair-Id=K3ESJI6DHPFC7). We are sorry for the inconvenience. Please retry with `force_download=True`.
If the issue persists, please let us know by opening an issue on https://github.com/huggingface/huggingface_hub."

An interesting thing to point out is that when running the below example -  the file size increases marginally. 

### Reproduction

from samgeo.text_sam import LangSAM

sam = LangSAM()

### System info

```shell
- huggingface_hub version: 0.24.6
- Platform: Windows-10-10.0.22631-SP0
- Python version: 3.9.19
- Running in iPython ?: Yes
- iPython shell: ZMQInteractiveShell
- Running in notebook ?: Yes
- Running in Google Colab ?: No
- Token path ?: C:\Users\cdornan\.cache\huggingface\token
- Has saved token ?: False
- Configured git credential helpers: manager
- FastAI: N/A
- Tensorflow: N/A
- Torch: 2.4.0
- Jinja2: 3.1.4
- Graphviz: N/A
- keras: N/A
- Pydot: N/A
- Pillow: 10.4.0
- hf_transfer: N/A
- gradio: N/A
- tensorboard: 2.6.2.2
- numpy: 1.26.4
- pydantic: 2.8.2
- aiohttp: 3.10.5
- ENDPOINT: https://huggingface.co
- HF_HUB_CACHE: C:\Users\cdornan\.cache\huggingface\hub
- HF_ASSETS_CACHE: C:\Users\cdornan\.cache\huggingface\assets
- HF_TOKEN_PATH: C:\Users\cdornan\.cache\huggingface\token
- HF_HUB_OFFLINE: False
- HF_HUB_DISABLE_TELEMETRY: False
- HF_HUB_DISABLE_PROGRESS_BARS: None
- HF_HUB_DISABLE_SYMLINKS_WARNING: False
- HF_HUB_DISABLE_EXPERIMENTAL_WARNING: False
- HF_HUB_DISABLE_IMPLICIT_TOKEN: False
- HF_HUB_ENABLE_HF_TRANSFER: False
- HF_HUB_ETAG_TIMEOUT: 10
- HF_HUB_DOWNLOAD_TIMEOUT: 10
```

**Comment by Wauplin** [comment] 2024-09-09 14:44
Thanks for reporting and sorry for the inconvenience @Craig-Dornan. This seems to be a download issue. 

> An interesting thing to point out is that when running the below example - the file size increases marginally.

This is an interesting finding. It means a few bytes are downloaded before failing. Can you try to run:

```py
import logging
logging.basicConfig(level=logging.DEBUG)

from samgeo.text_sam import LangSAM

sam = LangSAM()
```

and copy-paste the full logs please? It might help us investigate.

**Comment by Craig-Dornan** [comment] 2024-09-09 14:49
DEBUG:urllib3.connectionpool:https://huggingface.co:443 "HEAD /bert-base-uncased/resolve/main/config.json HTTP/11" 200 0
DEBUG:urllib3.connectionpool:https://huggingface.co:443 "HEAD /bert-base-uncased/resolve/main/config.json HTTP/11" 200 0
DEBUG:urllib3.connectionpool:https://huggingface.co:443 "HEAD /bert-base-uncased/resolve/main/model.safetensors HTTP/11" 302 0
DEBUG:filelock:Attempting to acquire lock 2179615178224 on C:\Users\cdornan\.cache\huggingface\hub\.locks\models--bert-base-uncased\68d45e234eb4a928074dfd868cead0219ab85354cc53d20e772753c6bb9169d3.lock
DEBUG:filelock:Lock 2179615178224 acquired on C:\Users\cdornan\.cache\huggingface\hub\.locks\models--bert-base-uncased\68d45e234eb4a928074dfd868cead0219ab85354cc53d20e772753c6bb9169d3.lock
DEBUG:urllib3.connectionpool:Resetting dropped connection: cdn-lfs.huggingface.co
DEBUG:urllib3.connectionpool:https://cdn-lfs.huggingface.co:443 "GET /bert-base-uncased/68d45e234eb4a928074dfd868cead0219ab85354cc53d20e772753c6bb9169d3?response-content-disposition=inline%3B+filename*%3DUTF-8%27%27model.safetensors%3B+filename%3D%22model.safetensors%22%3B&Expires=1726151443&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcyNjE1MTQ0M319LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9iZXJ0LWJhc2UtdW5jYXNlZC82OGQ0NWUyMzRlYjRhOTI4MDc0ZGZkODY4Y2VhZDAyMTlhYjg1MzU0Y2M1M2QyMGU3NzI3NTNjNmJiOTE2OWQzP3Jlc3BvbnNlLWNvbnRlbnQtZGlzcG9zaXRpb249KiJ9XX0_&Signature=IPn8OcfU7IGkN~meJoU1gmjLZvVdggdhHZ6-yiji~ZhhwwE8FPeKus53lc2v66VJ2WwDHZlVPwWQA5nZwY3aVoK4vBrf8XJHCZyT-BIZ~GAsDFqaEj9H7nKYMSSBCpK8waWMKhu5XFLx5~dAU06One9iV8dNYXDVUEKStOU0Xtyr5apKcJOXXtDlA4O1Q26NkiRXUl-B~Gm448kxjgoG53hbWRalvrICZLVod~ir758iQi7goE2IVHBxfB-BatqoMm8d3O-rQx5Ip0MAcBdpip4MKGOx8RV-3KbTm5T7xwxgTmYPRWmD6VrkQ4vLv5GNNxhMg1xS1LYUj1zauCdkUA__&Key-Pair-Id=K3ESJI6DHPFC7 HTTP/11" 303 None
DEBUG:urllib3.connectionpool:Resetting dropped connection: g-8d838cb2321d4b9b461e5f533824bb72.checkpoint.cloud
DEBUG:urllib3.connectionpool:https://g-8d838cb2321d4b9b461e5f533824bb72.checkpoint.cloud:443 "GET /UserCheck/PortalMain?IID=591651ED-5540-8EE8-900E-9C323D4B2103&origUrl=aHR0cHM6Ly9jZG4tbGZzLmh1Z2dpbmdmYWNlLmNvL2JlcnQtYmFzZS11bmNhc2VkLzY4ZDQ1ZTIzNGViNGE5MjgwNzRkZmQ4NjhjZWFkMDIxOWFiODUzNTRjYzUzZDIwZTc3Mjc1M2M2YmI5MTY5ZDM_cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj1pbmxpbmU7IGZpbGVuYW1lKj1VVEYtOCcnbW9kZWwuc2FmZXRlbnNvcnM7IGZpbGVuYW1lPSJtb2RlbC5zYWZldGVuc29ycyI7JkV4cGlyZXM9MTcyNjE1MTQ0MyZQb2xpY3k9ZXlKVGRHRjBaVzFsYm5RaU9sdDdJa052Ym1ScGRHbHZiaUk2ZXlKRVlYUmxUR1Z6YzFSb1lXNGlPbnNpUVZkVE9rVndiMk5vVkdsdFpTSTZNVGN5TmpFMU1UUTBNMzE5TENKU1pYTnZkWEpqWlNJNkltaDBkSEJ6T2k4dlkyUnVMV3htY3k1b2RXZG5hVzVuWm1GalpTNWpieTlpWlhKMExXSmhjMlV0ZFc1allYTmxaQzgyT0dRME5XVXlNelJsWWpSaE9USTRNRGMwWkdaa09EWTRZMlZoWkRBeU1UbGhZamcxTXpVMFkyTTFNMlF5TUdVM056STNOVE5qTm1KaU9URTJPV1F6UDNKbGMzQnZibk5sTFdOdmJuUmxiblF0WkdsemNHOXphWFJwYjI0OUtpSjlYWDBfJlNpZ25hdHVyZT1JUG44T2NmVTdJR2tOfm1lSm9VMWdtakxadlZkZ2dkaEhaNi15aWppflpoaHd3RThGUGVLdXM1M2xjMnY2NlZKMld3REhabFZQd1dRQTVuWndZM2FWb0s0dkJyZjhYSkhDWnlULUJJWn5HQXNERnFhRWo5SDduS1lNU1NCQ3BLOHdhV01LaHU1WEZMeDV-ZEFVMDZPbmU5aVY4ZE5ZWERWVUVLU3RPVTBYdHlyNWFwS2NKT1hYdERsQTRPMVEyNk5raVJYVWwtQn5HbTQ0OGt4amdvRzUzaGJXUmFsdnJJQ1pMVm9kfmlyNzU4aVFpN2dvRTJJVkhCeGZCLUJhdHFvTW04ZDNPLXJReDVJcDBNQWNCZHBpcDRNS0dPeDhSVi0zS2JUbTVUN3h3eGdUbVlQUldtRDZWcmtRNHZMdjVHTk54aE1nMXhTMUxZVWoxemF1Q2RrVUFfXyZLZXktUGFpci1JZD1LM0VTSkk2REhQRkM3 HTTP/11" 200 None

**Comment by Wauplin** [comment] 2024-09-10 15:51
Is this the whole stacktrace? You get only these logs and then the `OSError: Consistency check failed`?

**Comment by Craig-Dornan** [comment] 2024-09-11 07:43
yeah - that all the output I'm getting.

**Comment by Craig-Dornan** [comment] 2024-09-12 12:52
![image](https://github.com/user-attachments/assets/a5f8ff66-1135-45f6-92ad-ebe5632a011b)
![image](https://github.com/user-attachments/assets/0de90e18-5eda-488e-a4e1-7d3880453a8d)

**Comment by hanouticelina** [comment] 2024-10-10 09:35
close as duplicate of #2589

**Closed by hanouticelina** 2024-10-10 09:35 UTC
Labels: bug
