### ISSUE TITLE
ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true

### ISSUE THREAD

**Issue by SamuriAi** [huggingface/huggingface_hub#2624] opened 2024-10-22 04:28 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Wauplin** [comment] 2024-10-22 12:38
Please explain in more details what's the issue is about. In the meantime, I'll just close it

**Closed by Wauplin** 2024-10-22 12:38 UTC
