### ISSUE TITLE
AttributeError: type object 'tqdm' has no attribute '_lock'

### ISSUE THREAD

**Issue by NielsRogge** [huggingface/huggingface_hub#1603] opened 2023-08-09 14:53 UTC
### Describe the bug

Getting a tqdm issue when writing a Dask dataframe to the hub.

Similar to huggingface/datasets#6066. Using latest Datasets version doesn't seem to resolve it

### Steps to reproduce the bug

This is a minimal reproducer:
```
import dask.dataframe as dd
import pandas as pd
import random

import huggingface_hub

data = {"number": [random.randint(0,10) for _ in range(1000)]}
df = pd.DataFrame.from_dict(data)
dataframe = dd.from_pandas(df, npartitions=1)
dataframe = dataframe.repartition(npartitions=2)

repo_id = "nielsr/test-dask"
repo_path = f"hf://datasets/{repo_id}"
huggingface_hub.create_repo(repo_id=repo_id, repo_type="dataset", exist_ok=True)
dd.to_parquet(dataframe, path=f"{repo_path}/data")
```
Note: I'm intentionally repartioning the Dask dataframe to 2 partitions, as it does work when only having one partition. 

### Expected behavior

Would expect to write to the hub without any problem.

### Environment info

Datasets version 2.14.4

**Comment by Wauplin** [comment] 2023-08-18 13:08
@NielsRogge What's your full stacktrace? And which version of `tqdm` are you using ?

```
pip freeze [ grep tqdm
```

**Comment by Wauplin** [comment] 2023-08-18 13:11
Ah I see, so the issue has already being identified and fixed in https://github.com/huggingface/datasets/pull/6068 ?
We can make the exact same fix for `huggingface_hub` as well. But very weird that I can't reproduce myself and that no-one complained so far :confused:

**Closed** 2023-08-29 14:04 UTC
