### ISSUE TITLE
BadRequestError due to python/tuple in YAML

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/huggingface_hub#1950] opened 2024-01-03 13:41 UTC
### Describe the bug

I get a `BadRequestError` for dataset https://huggingface.co/datasets/capes, when making push to hub.

Maybe the issue is caused by the underlying service API.

- Note that one of the features of this dataset is the `translation`, with a Python tuple:
```yaml
dataset_info:
  features:
  - name: translation
    dtype:
      translation:
        languages:
        - en
        - pt
```

### Logs

```shell
BadRequestError:  (Request ID: Root=1-659558eb-7c4f530f1c1f560317f09223;85312e92-4e2a-4e94-ba08-2409317d4d45)

Bad request for commit endpoint:
Invalid YAML in README.md: unknown tag !<tag:yaml.org,2002:python/tuple> (33:3)

 30 |         languages: !!python/tuple
 31 |         - en
 32 |         - pt
 33 |   splits:
--------^
 34 |   - name: train
 35 |     num_bytes: 472483436
```
```


### System info

```shell
- huggingface_hub version: 0.21.0.dev0
- Platform: Linux-5.15.0-91-generic-x86_64-with-glibc2.31
- Python version: 3.9.7
```

**Comment by Wauplin** [comment] 2024-01-03 13:56
Indeed, it looks like an error raised server-side when validating the yaml. @albertvillanova could you provide a reproducible script that raises the error? Based on your example, I ran this script that downloads the README file, create a new dataset repo and upload the README file with "broken" metadata part:

```py
from huggingface_hub import create_repo, hf_hub_download, upload_file


readme_file = hf_hub_download("capes", repo_type="dataset", filename="README.md")

repo_url = create_repo("tmp_metadata", exist_ok=True, repo_type="dataset")
print(repo_url)

upload_file(path_or_fileobj=readme_file, path_in_repo="README.md", repo_id=repo_url.repo_id, repo_type="dataset")
```

And the README got correctly uploaded: https://huggingface.co/datasets/Wauplin/tmp_metadata.

**Comment by albertvillanova** [comment] 2024-01-05 10:10
Unfortunately, I'm not able to reproduce the issue: it seems there is some randomness taking place...

If I finally manage to reproduce one case, I will report it here.

**Comment by Wauplin** [comment] 2024-01-05 14:52
Ok, thanks for trying to reproduce. In the meantime I'll keep this issue open.

**Comment by Wauplin** [comment] 2024-01-22 15:28
EDIT: for now I'll close it and if it ever happens again, either comment on this issue or open a new one (I'm doing some cleaning of the ongoing issues)

**Closed by Wauplin** 2024-01-22 15:28 UTC
Labels: bug
