### ISSUE TITLE
Is it possible to drop everything inside the main branch before creating a new branch?

### ISSUE THREAD

**Issue by camenduru** [huggingface/huggingface_hub#1288] opened 2023-01-09 14:59 UTC
Is it possible to add a flag to `create_branch` that would allow everything from the main branch to be dropped when creating a new branch? For example, `create_branch(orphan=true)`

**Comment by julien-c** [comment] 2023-01-09 20:14
sounds reasonable to me from quick glance

I'm also wondering if we have a way to create a branch from a specific commit (i don't remember 🤔 ) – as you could programmatically create a branch from the initial commit on `main`

**Comment by coyotte508** [comment] 2023-01-16 11:03
no issues, created an internal issue

**Comment by Wauplin** [comment] 2023-01-16 16:34
Makes sense :+1:  I'll keep you updated about our internal progress :)

I'm cc-ing @patrickvonplaten @SBrandeis @apolinario @julien-c @osanseviero @LysandreJik if you want to add something on this topic as I remember the "how should we handle different variations of the same weights"-question  has been [heavily discussed](https://huggingface.slack.com/archives/C021H1P1HKR/p1670838413578579) internally (private thread). Decision was to encourage further to have all checkpoints on the same branch but some adjustments have to be made to the existing libraries, so it's more a mid-term perspective.

**Comment by camenduru** [comment] 2023-01-16 16:57
thanks @Wauplin ❤ if we put all the checkpoints in the same branch and If people only want to use the flax models, they have to clone 4000000GB of data maybe more 😋

**Comment by camenduru** [comment] 2023-01-16 17:01
When I first heard the idea from @patrickvonplaten, it sounded cool, but when I tried using the idea, I found that we should put everything in different branches, this is the way 😋

**Comment by Wauplin** [comment] 2023-01-18 10:08
@camenduru I just merged https://github.com/huggingface/huggingface_hub/pull/1293 which allows you to create a branch from any given revision. As mentioned in https://github.com/huggingface/huggingface_hub/pull/1293#issue-1536352063, you still need to know the initial commit hash in order to create a branch from it. 
If that is enough for your use case, you can close this issue. Otherwise, let's keep it open to remember about having an endpoint to retrieve the git history (note: we already have [an internal issue](https://github.com/huggingface/moon-landing/issues/5135) for that but it might not be implemented before next release of `hfh`)

**Comment by camenduru** [comment] 2023-01-19 19:30
I will try this `git rev-list --max-parents=0 HEAD`

**Comment by Wauplin** [comment] 2023-01-20 08:50
Yep, I understand the problem of not having a `get_first_revision_hash`-like helper in the API at the moment (or something like `initial=True`). The problem is that it requires to add a new endpoint server-side. This is still not done (and will not be done before `hfh v0.12`) but we have an [internal ticket](https://github.com/huggingface/moon-landing/issues/5135) to track the feature request.

About `git rev-list --max-parents=0 HEAD`, that's true it's a solution but only if you've clone the repo locally. The goal of `create_branch(repo_id, branch="branch", initial=True)` would be to have this helper using only HTTP endpoints.

**Comment by Wauplin** [comment] 2023-02-10 11:17
Server-side implementation is done, PR is on its way to have it in `huggingface_hub` @camenduru :wink: https://github.com/huggingface/huggingface_hub/pull/1331

**Closed** 2023-02-16 08:41 UTC
